using Microsoft.Data.Sqlite;
using SoftwareCatalog.Core.Abstractions;
using SoftwareCatalog.Core.Domain;
using SoftwareCatalog.Database.Migrations;

namespace SoftwareCatalog.Database;
public sealed class CatalogDatabase(string databasePath, IAppLogger? logger = null) : IScanCatalogRepository, IProductCatalogRepository, IDownloadHistoryRepository
{
    private readonly string _connectionString = new SqliteConnectionStringBuilder { DataSource = databasePath, Mode = SqliteOpenMode.ReadWriteCreate, Cache = SqliteCacheMode.Shared, Pooling = false }.ToString();
    private static readonly IMigration[] Migrations = [new Migration001Initial(), new Migration002CaseInsensitivePaths(), new Migration003InstallerMetadata(), new Migration004PackageList(), new Migration005ProductsAndUpdates(), new Migration006Downloads()];
    public async Task InitializeAsync(CancellationToken cancellationToken)
    {
        try { Directory.CreateDirectory(Path.GetDirectoryName(databasePath)!); await using var connection = await OpenAsync(cancellationToken); await using (var command = connection.CreateCommand()) { command.CommandText = "CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_utc TEXT NOT NULL);"; await command.ExecuteNonQueryAsync(cancellationToken); } await new MigrationRunner(Migrations, logger).ApplyAsync(connection, cancellationToken); }
        catch (Exception exception) { LogOperationError("Initialize", $"databasePath={databasePath}", exception); throw; }
    }
    public async Task<IReadOnlyList<ScanRoot>> GetScanRootsAsync(CancellationToken token) { try { var result = new List<ScanRoot>(); await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT id,stored_path,path_kind,include_subdirectories,enabled,created_utc,updated_utc FROM scan_roots ORDER BY id"; await using var r = await cmd.ExecuteReaderAsync(token); while (await r.ReadAsync(token)) result.Add(new(r.GetInt64(0), r.GetString(1), (ScanRootPathKind)r.GetInt32(2), r.GetBoolean(3), r.GetBoolean(4), DateTimeOffset.Parse(r.GetString(5)), DateTimeOffset.Parse(r.GetString(6)))); return result; } catch (Exception exception) { LogOperationError("GetScanRoots", $"databasePath={databasePath}", exception); throw; } }
    public async Task<ScanRoot> AddScanRootAsync(string path, ScanRootPathKind kind, bool include, CancellationToken token) { try { var now = DateTimeOffset.UtcNow; await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "INSERT INTO scan_roots(stored_path,path_kind,include_subdirectories,enabled,created_utc,updated_utc) VALUES($p,$k,$i,1,$now,$now); SELECT last_insert_rowid();"; cmd.Parameters.AddWithValue("$p", path); cmd.Parameters.AddWithValue("$k", (int)kind); cmd.Parameters.AddWithValue("$i", include); cmd.Parameters.AddWithValue("$now", now.ToString("O")); var id = Convert.ToInt64(await cmd.ExecuteScalarAsync(token)); return new(id, path, kind, include, true, now, now); } catch (Exception exception) { LogOperationError("AddScanRoot", $"path={path} pathKind={kind} includeSubdirectories={include}", exception); throw; } }
    public async Task RemoveScanRootAsync(long id, CancellationToken token) { try { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "DELETE FROM scan_roots WHERE id=$id"; cmd.Parameters.AddWithValue("$id", id); await cmd.ExecuteNonQueryAsync(token); } catch (Exception exception) { LogOperationError("RemoveScanRoot", $"rootId={id}", exception); throw; } }
    public async Task UpdateScanRootAsync(long id, string path, ScanRootPathKind kind, CancellationToken token) { try { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "UPDATE scan_roots SET stored_path=$path,path_kind=$kind,updated_utc=$now WHERE id=$id"; cmd.Parameters.AddWithValue("$id", id); cmd.Parameters.AddWithValue("$path", path); cmd.Parameters.AddWithValue("$kind", (int)kind); cmd.Parameters.AddWithValue("$now", DateTimeOffset.UtcNow.ToString("O")); await cmd.ExecuteNonQueryAsync(token); } catch (Exception exception) { LogOperationError("UpdateScanRoot", $"rootId={id} path={path}", exception); throw; } }
    public async Task<InstallerFile?> FindInstallerAsync(long root, string relative, CancellationToken token) { try { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = FileSelect + " WHERE scan_root_id=$root AND relative_path=$path"; cmd.Parameters.AddWithValue("$root", root); cmd.Parameters.AddWithValue("$path", relative); await using var r = await cmd.ExecuteReaderAsync(token); return await r.ReadAsync(token) ? ReadFile(r) : null; } catch (Exception exception) { LogOperationError("FindInstaller", $"rootId={root} relativePath={relative}", exception); throw; } }
    public async Task UpsertInstallersAsync(IReadOnlyList<InstallerFile> files, CancellationToken token) { if (files.Count == 0) return; try { await using var c = await OpenAsync(token); await using var t = await c.BeginTransactionAsync(token); foreach (var f in files) { await using var cmd = c.CreateCommand(); cmd.Transaction = (SqliteTransaction)t; cmd.CommandText = "INSERT INTO installer_files(scan_root_id,relative_path,file_name,extension,size,last_write_utc,sha256,first_seen_utc,last_seen_utc,exists_flag,installer_kind,product_name,product_version,publisher,file_version,file_description,architecture,metadata_source,metadata_status,metadata_error,normalized_version,product_code,upgrade_code,package_list) VALUES($r,$p,$n,$e,$s,$m,$h,$f,$l,1,$ik,$pn,$pv,$pub,$fv,$fd,$a,$ms,$mt,$me,$nv,$pc,$uc,$pl) ON CONFLICT(scan_root_id,relative_path) DO UPDATE SET file_name=excluded.file_name,extension=excluded.extension,size=excluded.size,last_write_utc=excluded.last_write_utc,sha256=excluded.sha256,last_seen_utc=excluded.last_seen_utc,exists_flag=1,installer_kind=excluded.installer_kind,product_name=excluded.product_name,product_version=excluded.product_version,publisher=excluded.publisher,file_version=excluded.file_version,file_description=excluded.file_description,architecture=excluded.architecture,metadata_source=excluded.metadata_source,metadata_status=excluded.metadata_status,metadata_error=excluded.metadata_error,normalized_version=excluded.normalized_version,product_code=excluded.product_code,upgrade_code=excluded.upgrade_code,package_list=excluded.package_list"; AddFileParameters(cmd, f); await cmd.ExecuteNonQueryAsync(token); await using var identity = c.CreateCommand(); identity.Transaction = (SqliteTransaction)t; identity.CommandText = "UPDATE installer_files SET msix_identity_name=$identity WHERE scan_root_id=$root AND relative_path=$path"; identity.Parameters.AddWithValue("$identity", (object?)f.MsixIdentityName ?? DBNull.Value); identity.Parameters.AddWithValue("$root", f.ScanRootId); identity.Parameters.AddWithValue("$path", f.RelativePath); await identity.ExecuteNonQueryAsync(token); } await t.CommitAsync(token); } catch (Exception exception) { LogOperationError("UpsertInstallers", $"fileCount={files.Count} rootId={files[0].ScanRootId}", exception); throw; } }
    public async Task MarkMissingAsync(long root, DateTimeOffset started, CancellationToken token) { try { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "UPDATE installer_files SET exists_flag=0 WHERE scan_root_id=$root AND last_seen_utc < $started"; cmd.Parameters.AddWithValue("$root", root); cmd.Parameters.AddWithValue("$started", started.ToString("O")); await cmd.ExecuteNonQueryAsync(token); } catch (Exception exception) { LogOperationError("MarkMissing", $"rootId={root} startedUtc={started:O}", exception); throw; } }
    public async Task<IReadOnlyList<InstallerFile>> GetInstallersAsync(CancellationToken token) { try { var files = new List<InstallerFile>(); await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = FileSelect + " ORDER BY id"; await using var r = await cmd.ExecuteReaderAsync(token); while (await r.ReadAsync(token)) files.Add(ReadFile(r)); return files; } catch (Exception exception) { LogOperationError("GetInstallers", $"databasePath={databasePath}", exception); throw; } }
    public async Task<IReadOnlyList<SoftwareProduct>> GetProductsAsync(CancellationToken token) { var list = new List<SoftwareProduct>(); await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT id,canonical_name,publisher,normalized_name,created_utc,updated_utc,latest_local_version,latest_normalized_version,update_status,latest_version,update_provider,external_product_id,last_checked_utc,update_error FROM software_products ORDER BY canonical_name"; await using var r = await cmd.ExecuteReaderAsync(token); while (await r.ReadAsync(token)) list.Add(ReadProduct(r)); return list; }
    public async Task<IReadOnlyList<InstallerFile>> GetInstallersForProductAsync(Guid id, CancellationToken token) { var list = new List<InstallerFile>(); await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = FileSelect + " WHERE product_id=$id ORDER BY normalized_version"; cmd.Parameters.AddWithValue("$id", id.ToString()); await using var r = await cmd.ExecuteReaderAsync(token); while (await r.ReadAsync(token)) list.Add(ReadFile(r)); return list; }
    public async Task<SoftwareProduct> UpsertProductAsync(SoftwareProduct product, CancellationToken token) { var now = DateTimeOffset.UtcNow; var value = product with { UpdatedUtc = now }; await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "INSERT INTO software_products(id,canonical_name,publisher,normalized_name,created_utc,updated_utc,latest_local_version,latest_normalized_version,update_status,latest_version,update_provider,external_product_id,last_checked_utc,update_error) VALUES($id,$n,$p,$nn,$c,$u,$ll,$ln,$s,$lv,$up,$ep,$lc,$e) ON CONFLICT(id) DO UPDATE SET canonical_name=excluded.canonical_name,publisher=excluded.publisher,normalized_name=excluded.normalized_name,updated_utc=excluded.updated_utc,latest_local_version=excluded.latest_local_version,latest_normalized_version=excluded.latest_normalized_version"; AddProduct(cmd, value); await cmd.ExecuteNonQueryAsync(token); return value; }
    public async Task LinkInstallerAsync(long installerId, Guid productId, ProductMatchSource source, ProductMatchConfidence confidence, CancellationToken token) { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "UPDATE installer_files SET product_id=$p,product_match_source=$s,product_match_confidence=$c WHERE id=$id"; cmd.Parameters.AddWithValue("$p",productId.ToString()); cmd.Parameters.AddWithValue("$s",(int)source); cmd.Parameters.AddWithValue("$c",(int)confidence); cmd.Parameters.AddWithValue("$id",installerId); await cmd.ExecuteNonQueryAsync(token); }
    public async Task<IReadOnlyList<ProductUpdateSource>> GetUpdateSourcesAsync(Guid productId, CancellationToken token) { var list = new List<ProductUpdateSource>(); await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT id,product_id,provider_type,external_id,enabled,is_explicit FROM product_update_sources WHERE product_id=$p"; cmd.Parameters.AddWithValue("$p",productId.ToString()); await using var r = await cmd.ExecuteReaderAsync(token); while(await r.ReadAsync(token)) list.Add(new(Guid.Parse(r.GetString(0)),Guid.Parse(r.GetString(1)),r.GetString(2),r.GetString(3),r.GetBoolean(4),r.GetBoolean(5))); return list; }
    public async Task SetUpdateSourceAsync(ProductUpdateSource source, CancellationToken token) { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "INSERT INTO product_update_sources(id,product_id,provider_type,external_id,enabled,is_explicit) VALUES($id,$p,$t,$e,$n,$x) ON CONFLICT(product_id,provider_type) DO UPDATE SET external_id=excluded.external_id,enabled=excluded.enabled,is_explicit=excluded.is_explicit"; cmd.Parameters.AddWithValue("$id",source.Id.ToString()); cmd.Parameters.AddWithValue("$p",source.ProductId.ToString()); cmd.Parameters.AddWithValue("$t",source.ProviderType); cmd.Parameters.AddWithValue("$e",source.ExternalId); cmd.Parameters.AddWithValue("$n",source.Enabled); cmd.Parameters.AddWithValue("$x",source.IsExplicit); await cmd.ExecuteNonQueryAsync(token); }
    public async Task ClearUpdateSourcesAsync(Guid productId, string providerType, CancellationToken token) { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "DELETE FROM product_update_sources WHERE product_id=$p AND provider_type=$t"; cmd.Parameters.AddWithValue("$p",productId.ToString()); cmd.Parameters.AddWithValue("$t",providerType); await cmd.ExecuteNonQueryAsync(token); }
    public async Task SaveUpdateCheckAsync(Guid id, UpdateCheckResult result, CancellationToken token) { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "UPDATE software_products SET update_status=$s,latest_version=$v,latest_normalized_version=$n,update_provider=$p,external_product_id=$e,last_checked_utc=$c,update_error=$r,updated_utc=$c WHERE id=$id"; cmd.Parameters.AddWithValue("$id",id.ToString()); cmd.Parameters.AddWithValue("$s",(int)result.Status); cmd.Parameters.AddWithValue("$v",(object?)result.LatestVersion??DBNull.Value); cmd.Parameters.AddWithValue("$n",(object?)result.LatestNormalizedVersion??DBNull.Value); cmd.Parameters.AddWithValue("$p",(object?)result.Source??DBNull.Value); cmd.Parameters.AddWithValue("$e",(object?)result.ExternalProductId??DBNull.Value); cmd.Parameters.AddWithValue("$c",(result.CheckedUtc??DateTimeOffset.UtcNow).ToString("O")); cmd.Parameters.AddWithValue("$r",(object?)result.Error??DBNull.Value); await cmd.ExecuteNonQueryAsync(token); }
    public async Task SaveDownloadHistoryAsync(DownloadHistory h, CancellationToken token) { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "INSERT INTO download_history(id,product_id,provider_type,external_product_id,version,file_name,source_url,expected_sha256,actual_sha256,status,error,started_utc,completed_utc,final_relative_path) VALUES($id,$p,$pt,$e,$v,$f,$u,$x,$a,$s,$r,$st,$c,$q) ON CONFLICT(id) DO UPDATE SET actual_sha256=excluded.actual_sha256,status=excluded.status,error=excluded.error,completed_utc=excluded.completed_utc,final_relative_path=excluded.final_relative_path"; cmd.Parameters.AddWithValue("$id",h.Id.ToString()); cmd.Parameters.AddWithValue("$p",h.ProductId.ToString()); cmd.Parameters.AddWithValue("$pt",h.ProviderType); cmd.Parameters.AddWithValue("$e",h.ExternalProductId); cmd.Parameters.AddWithValue("$v",(object?)h.Version??DBNull.Value); cmd.Parameters.AddWithValue("$f",(object?)h.FileName??DBNull.Value); cmd.Parameters.AddWithValue("$u",(object?)h.SourceUrl??DBNull.Value); cmd.Parameters.AddWithValue("$x",(object?)h.ExpectedSha256??DBNull.Value); cmd.Parameters.AddWithValue("$a",(object?)h.ActualSha256??DBNull.Value); cmd.Parameters.AddWithValue("$s",(int)h.Status); cmd.Parameters.AddWithValue("$r",(object?)h.Error??DBNull.Value); cmd.Parameters.AddWithValue("$st",h.StartedUtc.ToString("O")); cmd.Parameters.AddWithValue("$c",h.CompletedUtc?.ToString("O")??(object)DBNull.Value); cmd.Parameters.AddWithValue("$q",(object?)h.FinalRelativePath??DBNull.Value); await cmd.ExecuteNonQueryAsync(token); }
    public async Task<IReadOnlyList<DownloadHistory>> GetDownloadHistoryAsync(CancellationToken token) { var list = new List<DownloadHistory>(); await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT id,product_id,provider_type,external_product_id,version,file_name,source_url,expected_sha256,actual_sha256,status,error,started_utc,completed_utc,final_relative_path FROM download_history ORDER BY started_utc DESC"; await using var r = await cmd.ExecuteReaderAsync(token); while(await r.ReadAsync(token)) list.Add(new(Guid.Parse(r.GetString(0)),Guid.Parse(r.GetString(1)),r.GetString(2),r.GetString(3),Text(r,4),Text(r,5),Text(r,6),Text(r,7),Text(r,8),(DownloadStatus)r.GetInt32(9),Text(r,10),DateTimeOffset.Parse(r.GetString(11)),r.IsDBNull(12)?null:DateTimeOffset.Parse(r.GetString(12)),Text(r,13))); return list; }
    public async Task<bool> HasInstallerSha256Async(string hash, CancellationToken token) { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT EXISTS(SELECT 1 FROM installer_files WHERE sha256=$h)"; cmd.Parameters.AddWithValue("$h", hash); return Convert.ToInt64(await cmd.ExecuteScalarAsync(token)) != 0; }
    private async Task<SqliteConnection> OpenAsync(CancellationToken token) { var c = new SqliteConnection(_connectionString); await c.OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;"; await cmd.ExecuteNonQueryAsync(token); return c; }
    private void LogOperationError(string operation, string context, Exception exception) => logger?.Error(operation, $"operation={operation} context={context} error={exception.Message}");
    private const string FileSelect = "SELECT id,scan_root_id,relative_path,file_name,extension,size,last_write_utc,sha256,first_seen_utc,last_seen_utc,exists_flag,installer_kind,product_name,product_version,publisher,file_version,file_description,architecture,metadata_source,metadata_status,metadata_error,normalized_version,product_code,upgrade_code,package_list,product_id,product_match_source,product_match_confidence,msix_identity_name FROM installer_files";
    private static InstallerFile ReadFile(SqliteDataReader r) => new(r.GetInt64(0),r.GetInt64(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetInt64(5),DateTimeOffset.Parse(r.GetString(6)),r.IsDBNull(7)?null:r.GetString(7),DateTimeOffset.Parse(r.GetString(8)),DateTimeOffset.Parse(r.GetString(9)),r.GetBoolean(10),(InstallerKind)r.GetInt32(11),Text(r,12),Text(r,13),Text(r,14),Text(r,15),Text(r,16),Text(r,17),(MetadataSource)r.GetInt32(18),(MetadataStatus)r.GetInt32(19),Text(r,20),Text(r,21),Text(r,22),Text(r,23),Text(r,24),r.IsDBNull(25)?null:Guid.Parse(r.GetString(25)),r.IsDBNull(26)?null:(ProductMatchSource)r.GetInt32(26),r.IsDBNull(27)?null:(ProductMatchConfidence)r.GetInt32(27),Text(r,28));
    private static SoftwareProduct ReadProduct(SqliteDataReader r) => new(Guid.Parse(r.GetString(0)),r.GetString(1),Text(r,2),r.GetString(3),DateTimeOffset.Parse(r.GetString(4)),DateTimeOffset.Parse(r.GetString(5)),Text(r,6),Text(r,7),(UpdateStatus)r.GetInt32(8),Text(r,9),Text(r,10),Text(r,11),r.IsDBNull(12)?null:DateTimeOffset.Parse(r.GetString(12)),Text(r,13));
    private static void AddProduct(SqliteCommand c, SoftwareProduct p) { c.Parameters.AddWithValue("$id",p.Id.ToString()); c.Parameters.AddWithValue("$n",p.CanonicalName); c.Parameters.AddWithValue("$p",(object?)p.Publisher??DBNull.Value); c.Parameters.AddWithValue("$nn",p.NormalizedName); c.Parameters.AddWithValue("$c",p.CreatedUtc.ToString("O")); c.Parameters.AddWithValue("$u",p.UpdatedUtc.ToString("O")); c.Parameters.AddWithValue("$ll",(object?)p.LatestLocalVersion??DBNull.Value); c.Parameters.AddWithValue("$ln",(object?)p.LatestNormalizedVersion??DBNull.Value); c.Parameters.AddWithValue("$s",(int)p.UpdateStatus); c.Parameters.AddWithValue("$lv",(object?)p.LatestVersion??DBNull.Value); c.Parameters.AddWithValue("$up",(object?)p.UpdateProvider??DBNull.Value); c.Parameters.AddWithValue("$ep",(object?)p.ExternalProductId??DBNull.Value); c.Parameters.AddWithValue("$lc",p.LastCheckedUtc?.ToString("O")??(object)DBNull.Value); c.Parameters.AddWithValue("$e",(object?)p.UpdateError??DBNull.Value); }
    private static string? Text(SqliteDataReader r, int i) => r.IsDBNull(i) ? null : r.GetString(i);
    private static void AddFileParameters(SqliteCommand c, InstallerFile f) { c.Parameters.AddWithValue("$r",f.ScanRootId); c.Parameters.AddWithValue("$p",f.RelativePath); c.Parameters.AddWithValue("$n",f.FileName); c.Parameters.AddWithValue("$e",f.Extension); c.Parameters.AddWithValue("$s",f.Size); c.Parameters.AddWithValue("$m",f.LastWriteTimeUtc.ToString("O")); c.Parameters.AddWithValue("$h",(object?)f.Sha256??DBNull.Value); c.Parameters.AddWithValue("$f",f.FirstSeenUtc.ToString("O")); c.Parameters.AddWithValue("$l",f.LastSeenUtc.ToString("O")); c.Parameters.AddWithValue("$ik",(int)f.InstallerKind); c.Parameters.AddWithValue("$pn",(object?)f.ProductName??DBNull.Value); c.Parameters.AddWithValue("$pv",(object?)f.ProductVersion??DBNull.Value); c.Parameters.AddWithValue("$pub",(object?)f.Publisher??DBNull.Value); c.Parameters.AddWithValue("$fv",(object?)f.FileVersion??DBNull.Value); c.Parameters.AddWithValue("$fd",(object?)f.FileDescription??DBNull.Value); c.Parameters.AddWithValue("$a",(object?)f.Architecture??DBNull.Value); c.Parameters.AddWithValue("$ms",(int)f.MetadataSource); c.Parameters.AddWithValue("$mt",(int)f.MetadataStatus); c.Parameters.AddWithValue("$me",(object?)f.MetadataError??DBNull.Value); c.Parameters.AddWithValue("$nv",(object?)f.NormalizedVersion??DBNull.Value); c.Parameters.AddWithValue("$pc",(object?)f.ProductCode??DBNull.Value); c.Parameters.AddWithValue("$uc",(object?)f.UpgradeCode??DBNull.Value); c.Parameters.AddWithValue("$pl",(object?)f.PackageList??DBNull.Value); }
}
