using Microsoft.Data.Sqlite;
using SoftwareCatalog.Core.Abstractions;
using SoftwareCatalog.Core.Domain;
using SoftwareCatalog.Database.Migrations;

namespace SoftwareCatalog.Database;
public sealed class CatalogDatabase(string databasePath, IAppLogger? logger = null) : IScanCatalogRepository
{
    private readonly string _connectionString = new SqliteConnectionStringBuilder { DataSource = databasePath, Mode = SqliteOpenMode.ReadWriteCreate, Cache = SqliteCacheMode.Shared, Pooling = false }.ToString();
    private static readonly IMigration[] Migrations = [new Migration001Initial(), new Migration002CaseInsensitivePaths()];
    public async Task InitializeAsync(CancellationToken cancellationToken)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(databasePath)!); await using var connection = await OpenAsync(cancellationToken);
        await using (var command = connection.CreateCommand()) { command.CommandText = "CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_utc TEXT NOT NULL);"; await command.ExecuteNonQueryAsync(cancellationToken); }
        await new MigrationRunner(Migrations, logger).ApplyAsync(connection, cancellationToken);
    }
    public async Task<IReadOnlyList<ScanRoot>> GetScanRootsAsync(CancellationToken token) { var result = new List<ScanRoot>(); await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT id,stored_path,path_kind,include_subdirectories,enabled,created_utc,updated_utc FROM scan_roots ORDER BY id"; await using var r = await cmd.ExecuteReaderAsync(token); while (await r.ReadAsync(token)) result.Add(new(r.GetInt64(0), r.GetString(1), (ScanRootPathKind)r.GetInt32(2), r.GetBoolean(3), r.GetBoolean(4), DateTimeOffset.Parse(r.GetString(5)), DateTimeOffset.Parse(r.GetString(6)))); return result; }
    public async Task<ScanRoot> AddScanRootAsync(string path, ScanRootPathKind kind, bool include, CancellationToken token) { var now = DateTimeOffset.UtcNow; await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "INSERT INTO scan_roots(stored_path,path_kind,include_subdirectories,enabled,created_utc,updated_utc) VALUES($p,$k,$i,1,$now,$now); SELECT last_insert_rowid();"; cmd.Parameters.AddWithValue("$p", path); cmd.Parameters.AddWithValue("$k", (int)kind); cmd.Parameters.AddWithValue("$i", include); cmd.Parameters.AddWithValue("$now", now.ToString("O")); var id = Convert.ToInt64(await cmd.ExecuteScalarAsync(token)); return new(id, path, kind, include, true, now, now); }
    public async Task RemoveScanRootAsync(long id, CancellationToken token) { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "DELETE FROM scan_roots WHERE id=$id"; cmd.Parameters.AddWithValue("$id", id); await cmd.ExecuteNonQueryAsync(token); }
    public async Task UpdateScanRootAsync(long id, string path, ScanRootPathKind kind, CancellationToken token) { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "UPDATE scan_roots SET stored_path=$path,path_kind=$kind,updated_utc=$now WHERE id=$id"; cmd.Parameters.AddWithValue("$id", id); cmd.Parameters.AddWithValue("$path", path); cmd.Parameters.AddWithValue("$kind", (int)kind); cmd.Parameters.AddWithValue("$now", DateTimeOffset.UtcNow.ToString("O")); await cmd.ExecuteNonQueryAsync(token); }
    public async Task<InstallerFile?> FindInstallerAsync(long root, string relative, CancellationToken token) { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT id,scan_root_id,relative_path,file_name,extension,size,last_write_utc,sha256,first_seen_utc,last_seen_utc,exists_flag FROM installer_files WHERE scan_root_id=$root AND relative_path=$path"; cmd.Parameters.AddWithValue("$root", root); cmd.Parameters.AddWithValue("$path", relative); await using var r = await cmd.ExecuteReaderAsync(token); return await r.ReadAsync(token) ? ReadFile(r) : null; }
    public async Task UpsertInstallersAsync(IReadOnlyList<InstallerFile> files, CancellationToken token) { if (files.Count == 0) return; try { await using var c = await OpenAsync(token); await using var t = await c.BeginTransactionAsync(token); foreach (var f in files) { await using var cmd = c.CreateCommand(); cmd.Transaction = (SqliteTransaction)t; cmd.CommandText = "INSERT INTO installer_files(scan_root_id,relative_path,file_name,extension,size,last_write_utc,sha256,first_seen_utc,last_seen_utc,exists_flag) VALUES($r,$p,$n,$e,$s,$m,$h,$f,$l,1) ON CONFLICT(scan_root_id,relative_path) DO UPDATE SET file_name=excluded.file_name,extension=excluded.extension,size=excluded.size,last_write_utc=excluded.last_write_utc,sha256=excluded.sha256,last_seen_utc=excluded.last_seen_utc,exists_flag=1"; AddFileParameters(cmd, f); await cmd.ExecuteNonQueryAsync(token); } await t.CommitAsync(token); } catch (Exception exception) { logger?.Error("UpsertInstallers", $"fileCount={files.Count} rootId={files[0].ScanRootId}: {exception.Message}"); throw; } }
    public async Task MarkMissingAsync(long root, DateTimeOffset started, CancellationToken token) { await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "UPDATE installer_files SET exists_flag=0 WHERE scan_root_id=$root AND last_seen_utc < $started"; cmd.Parameters.AddWithValue("$root", root); cmd.Parameters.AddWithValue("$started", started.ToString("O")); await cmd.ExecuteNonQueryAsync(token); }
    public async Task<IReadOnlyList<InstallerFile>> GetInstallersAsync(CancellationToken token) { var files = new List<InstallerFile>(); await using var c = await OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT id,scan_root_id,relative_path,file_name,extension,size,last_write_utc,sha256,first_seen_utc,last_seen_utc,exists_flag FROM installer_files ORDER BY id"; await using var r = await cmd.ExecuteReaderAsync(token); while (await r.ReadAsync(token)) files.Add(ReadFile(r)); return files; }
    private async Task<SqliteConnection> OpenAsync(CancellationToken token) { try { var c = new SqliteConnection(_connectionString); await c.OpenAsync(token); await using var cmd = c.CreateCommand(); cmd.CommandText = "PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;"; await cmd.ExecuteNonQueryAsync(token); return c; } catch (Exception exception) { logger?.Error("database", $"Open databasePath={databasePath}: {exception.Message}"); throw; } }
    private static InstallerFile ReadFile(SqliteDataReader r) => new(r.GetInt64(0),r.GetInt64(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetInt64(5),DateTimeOffset.Parse(r.GetString(6)),r.IsDBNull(7)?null:r.GetString(7),DateTimeOffset.Parse(r.GetString(8)),DateTimeOffset.Parse(r.GetString(9)),r.GetBoolean(10));
    private static void AddFileParameters(SqliteCommand c, InstallerFile f) { c.Parameters.AddWithValue("$r",f.ScanRootId); c.Parameters.AddWithValue("$p",f.RelativePath); c.Parameters.AddWithValue("$n",f.FileName); c.Parameters.AddWithValue("$e",f.Extension); c.Parameters.AddWithValue("$s",f.Size); c.Parameters.AddWithValue("$m",f.LastWriteTimeUtc.ToString("O")); c.Parameters.AddWithValue("$h",(object?)f.Sha256??DBNull.Value); c.Parameters.AddWithValue("$f",f.FirstSeenUtc.ToString("O")); c.Parameters.AddWithValue("$l",f.LastSeenUtc.ToString("O")); }
}
