using System.Windows;
using System.Windows.Controls;
using SoftwareCatalog.UI.ViewModels;
namespace SoftwareCatalog.UI;
public partial class MainWindow : Window
{
    public MainWindow() { InitializeComponent(); Loaded += (_, _) => { AddDownloadButton(); AddArchiveControls(); AddInstalledSoftwareControls(); }; }
    private void AddInstalledSoftwareControls()
    {
        if (DataContext is not MainViewModel viewModel || viewModel.RefreshInstalledCommand is null) return;
        var products = FindGroup(this, "Продукты"); var dock = products?.Content as DockPanel; var panel = dock?.Children.OfType<StackPanel>().FirstOrDefault();
        if (panel is null || panel.Children.OfType<Button>().Any(button => Equals(button.Command, viewModel.RefreshInstalledCommand))) return;
        var open = new Button { Content = "Установленное ПО", Margin = new Thickness(8, 0, 0, 0) }; open.Click += (_, _) => ShowInstalledSoftware(viewModel); panel.Children.Add(open);
    }
    private void ShowInstalledSoftware(MainViewModel viewModel)
    {
        var grid = new DataGrid { ItemsSource = viewModel.InstalledSoftwareRows, AutoGenerateColumns = false, IsReadOnly = true, MinHeight = 360 };
        grid.Columns.Add(new DataGridTextColumn { Header = "Name", Binding = new System.Windows.Data.Binding("Name") }); grid.Columns.Add(new DataGridTextColumn { Header = "Installed version", Binding = new System.Windows.Data.Binding("InstalledVersion") }); grid.Columns.Add(new DataGridTextColumn { Header = "Publisher", Binding = new System.Windows.Data.Binding("Publisher") }); grid.Columns.Add(new DataGridTextColumn { Header = "Architecture", Binding = new System.Windows.Data.Binding("Architecture") }); grid.Columns.Add(new DataGridTextColumn { Header = "Source", Binding = new System.Windows.Data.Binding("Source") }); grid.Columns.Add(new DataGridTextColumn { Header = "Matched product", Binding = new System.Windows.Data.Binding("MatchedProduct") }); grid.Columns.Add(new DataGridTextColumn { Header = "Latest version", Binding = new System.Windows.Data.Binding("LatestVersion") }); grid.Columns.Add(new DataGridTextColumn { Header = "Update status", Binding = new System.Windows.Data.Binding("UpdateStatus") }); grid.Columns.Add(new DataGridTextColumn { Header = "Install location", Binding = new System.Windows.Data.Binding("InstallLocation") });
        var rows = System.Windows.Data.CollectionViewSource.GetDefaultView(viewModel.InstalledSoftwareRows); grid.ItemsSource = rows;
        grid.SetBinding(DataGrid.SelectedItemProperty, new System.Windows.Data.Binding(nameof(MainViewModel.SelectedInstalledSoftware)) { Mode = System.Windows.Data.BindingMode.TwoWay }); var refresh = new Button { Content = "Обновить inventory", Command = viewModel.RefreshInstalledCommand }; var bind = new Button { Content = "Привязать к продукту", Command = viewModel.BindInstalledCommand, Margin = new Thickness(8,0,0,0) }; var change = new Button { Content = "Изменить привязку", Command = viewModel.BindInstalledCommand, Margin = new Thickness(8,0,0,0) }; var clear = new Button { Content = "Очистить привязку", Command = viewModel.ClearInstalledBindingCommand, Margin = new Thickness(8,0,0,0) }; var controls = new StackPanel { Orientation = Orientation.Horizontal }; foreach(var filter in SoftwareCatalog.UI.InstalledSoftwareWorkflow.Filters) { var button=new Button { Content=filter.Label, Margin=new Thickness(8,0,0,0) }; button.Click+=(_,_)=>{rows.Filter=item=>item is SoftwareCatalog.Core.InstalledSoftwareRow row && SoftwareCatalog.UI.InstalledSoftwareWorkflow.Includes(row, filter.Filter);}; controls.Children.Add(button); } controls.Children.Add(refresh); controls.Children.Add(bind); controls.Children.Add(change); controls.Children.Add(clear); var panel = new DockPanel { Margin = new Thickness(12) }; DockPanel.SetDock(controls, Dock.Bottom); controls.Margin = new Thickness(0, 8, 0, 0); panel.Children.Add(controls); panel.Children.Add(grid); new Window { Title = "Установленное ПО", Content = panel, Owner = this, Width = 1200, Height = 520 }.ShowDialog();
    }
    private void AddDownloadButton()
    {
        if (DataContext is not MainViewModel viewModel) return;
        var products = FindGroup(this, "Продукты"); var dock = products?.Content as DockPanel; var panel = dock?.Children.OfType<StackPanel>().FirstOrDefault();
        if (dock is null || panel is null || panel.Children.OfType<Button>().Any(button => Equals(button.Command, viewModel.DownloadUpdateCommand))) return;
        var productGrid=dock.Children.OfType<DataGrid>().FirstOrDefault(); if(productGrid is not null && productGrid.Columns.All(column=>!Equals(column.Header,InstalledSoftwareWorkflow.ProductColumns[0].Header))) foreach(var column in InstalledSoftwareWorkflow.ProductColumns) productGrid.Columns.Add(column.IsCheckBox ? new DataGridCheckBoxColumn { Header=column.Header, Binding=new System.Windows.Data.Binding(column.BindingProperty) } : new DataGridTextColumn { Header=column.Header, Binding=new System.Windows.Data.Binding(column.BindingProperty) });
        panel.Children.Insert(Math.Min(3, panel.Children.Count), new Button { Content = "Скачать обновление", Command = viewModel.DownloadUpdateCommand, Margin = new Thickness(8, 0, 0, 0) });
        panel.Children.Insert(Math.Min(4, panel.Children.Count), new Button { Content = "История скачиваний", Command = viewModel.DownloadHistoryCommand, Margin = new Thickness(8, 0, 0, 0) });
        panel.Children.Insert(Math.Min(5, panel.Children.Count), new Button { Content = "Открыть папку", Command = viewModel.OpenDownloadFolderCommand, Margin = new Thickness(8, 0, 0, 0) });
        panel.Children.Add(new Button { Content = "Искать candidates", Command = viewModel.SearchCandidatesCommand, Margin = new Thickness(8, 0, 0, 0) });
        panel.Children.Add(new Button { Content = "Добавить alias", Command = viewModel.AddAliasCommand, Margin = new Thickness(8, 0, 0, 0) });
        panel.Children.Add(new Button { Content = "Удалить alias", Command = viewModel.RemoveAliasCommand, Margin = new Thickness(8, 0, 0, 0) });
        panel.Children.Add(new Button { Content = "Aliases", Command = viewModel.ListAliasesCommand, Margin = new Thickness(8, 0, 0, 0) });
        panel.Children.Add(new Button { Content = "Mappings", Command = viewModel.ShowMappingsCommand, Margin = new Thickness(8, 0, 0, 0) });
        panel.Children.Add(new Button { Content = "Enable/Disable mapping", Command = viewModel.ToggleMappingCommand, Margin = new Thickness(8, 0, 0, 0) });
        var retention = new Button { Content = "Анализ архива", Margin = new Thickness(8, 0, 0, 0) }; retention.Click += (_, _) => { viewModel.RetentionPreviewCommand.Execute(null); ShowRetention(viewModel); }; panel.Children.Add(retention);
        var archiveHistory = new Button { Content = "История архива", Margin = new Thickness(8, 0, 0, 0) }; archiveHistory.Click += async (_, _) => { await viewModel.RefreshArchiveOperationsAsync(); ShowArchiveHistory(viewModel); }; panel.Children.Add(archiveHistory);
        var progressPanel = new StackPanel { Margin = new Thickness(0, 4, 0, 0), Tag = "download-progress" }; var bar = new ProgressBar { Minimum = 0, Maximum = 100, Height = 14 }; bar.SetBinding(ProgressBar.ValueProperty, new System.Windows.Data.Binding(nameof(MainViewModel.DownloadPercent))); var text = new TextBlock(); text.SetBinding(TextBlock.TextProperty, new System.Windows.Data.Binding(nameof(MainViewModel.DownloadProgressText))); progressPanel.Children.Add(text); progressPanel.Children.Add(bar); DockPanel.SetDock(progressPanel, Dock.Bottom); dock.Children.Add(progressPanel);
        var archiveProgress = new StackPanel { Margin = new Thickness(0, 4, 0, 0), Tag = "archive-progress" }; var archiveBar = new ProgressBar { Minimum = 0, Maximum = 100, Height = 14 }; archiveBar.SetBinding(ProgressBar.ValueProperty, new System.Windows.Data.Binding(nameof(MainViewModel.ArchivePercent))); var archiveText = new TextBlock(); archiveText.SetBinding(TextBlock.TextProperty, new System.Windows.Data.Binding(nameof(MainViewModel.ArchiveProgressText))); archiveProgress.Children.Add(archiveText); archiveProgress.Children.Add(archiveBar); DockPanel.SetDock(archiveProgress, Dock.Bottom); dock.Children.Add(archiveProgress);
    }
    private void AddArchiveControls()
    {
        if (DataContext is not MainViewModel viewModel) return;
        var history = FindGroup(this, "Файлы выбранного продукта"); var files = history?.Content as DataGrid;
        if (history is null || files is null || history.Content is DockPanel) return;
        files.SetBinding(DataGrid.SelectedItemProperty, new System.Windows.Data.Binding(nameof(MainViewModel.SelectedFile)) { Mode = System.Windows.Data.BindingMode.TwoWay });
        files.Columns.Add(new DataGridTextColumn { Header = "Размер", Binding = new System.Windows.Data.Binding("Size") }); files.Columns.Add(new DataGridTextColumn { Header = "Состояние", Binding = new System.Windows.Data.Binding("StorageState") }); files.Columns.Add(new DataGridCheckBoxColumn { Header = "Закреплён", Binding = new System.Windows.Data.Binding("IsPinned") }); files.Columns.Add(new DataGridTextColumn { Header = "SHA-256", Binding = new System.Windows.Data.Binding("Sha256") }); files.Columns.Add(new DataGridTextColumn { Header = "Последнее обнаружение", Binding = new System.Windows.Data.Binding("LastSeenUtc") });
        var actions = new StackPanel { Orientation = Orientation.Horizontal, Margin = new Thickness(0, 0, 0, 8) };
        actions.Children.Add(new Button { Content = "Архивировать", Command = viewModel.ArchiveCommand }); actions.Children.Add(new Button { Content = "Восстановить", Command = viewModel.RestoreCommand, Margin = new Thickness(8,0,0,0) }); actions.Children.Add(new Button { Content = "В корзину", Command = viewModel.TrashCommand, Margin = new Thickness(8,0,0,0) }); actions.Children.Add(new Button { Content = "Закрепить / открепить", Command = viewModel.PinCommand, Margin = new Thickness(8,0,0,0) }); actions.Children.Add(new Button { Content = "Корзина", Margin = new Thickness(8,0,0,0) }); ((Button)actions.Children[^1]).Click += (_, _) => ShowTrash(viewModel);
        var dock = new DockPanel(); DockPanel.SetDock(actions, Dock.Top); dock.Children.Add(actions);
        history.Content = null;
        dock.Children.Add(files);
        history.Content = dock;
    }
    private void ShowTrash(MainViewModel viewModel)
    {
        var entries = viewModel.Files.Where(file => file.StorageState == SoftwareCatalog.Core.Domain.InstallerStorageState.Trashed).ToList(); var grid = new DataGrid { ItemsSource = entries, AutoGenerateColumns = false, IsReadOnly = true, MinHeight = 260 }; grid.Columns.Add(new DataGridTextColumn { Header = "Продукт", Binding = new System.Windows.Data.Binding("ProductName") }); grid.Columns.Add(new DataGridTextColumn { Header = "Версия", Binding = new System.Windows.Data.Binding("ProductVersion") }); grid.Columns.Add(new DataGridTextColumn { Header = "Файл", Binding = new System.Windows.Data.Binding("FileName") }); grid.Columns.Add(new DataGridTextColumn { Header = "Размер", Binding = new System.Windows.Data.Binding("Size") }); grid.Columns.Add(new DataGridTextColumn { Header = "Удалён", Binding = new System.Windows.Data.Binding("StorageChangedUtc") }); grid.Columns.Add(new DataGridTextColumn { Header = "Исходный путь", Binding = new System.Windows.Data.Binding("OriginalRelativePath") }); grid.Columns.Add(new DataGridTextColumn { Header = "SHA-256", Binding = new System.Windows.Data.Binding("Sha256") });
        var restore = new Button { Content = "Восстановить" }; var purge = new Button { Content = "Удалить окончательно", Margin = new Thickness(8,0,0,0) }; restore.Click += (_, _) => { if (grid.SelectedItem is SoftwareCatalog.Core.Domain.InstallerFile file) { viewModel.SelectedFile = file; viewModel.RestoreCommand.Execute(null); } }; purge.Click += (_, _) => { if (grid.SelectedItem is SoftwareCatalog.Core.Domain.InstallerFile file) { viewModel.SelectedFile = file; viewModel.PurgeCommand.Execute(null); } };
        var panel = new DockPanel { Margin = new Thickness(12) }; var buttons = new StackPanel { Orientation = Orientation.Horizontal, Margin = new Thickness(0,8,0,0) }; buttons.Children.Add(restore); buttons.Children.Add(purge); DockPanel.SetDock(buttons,Dock.Bottom); panel.Children.Add(buttons); panel.Children.Add(grid); new Window { Title = "Корзина", Content = panel, Owner = this, Width = 1000, Height = 420 }.ShowDialog();
    }
    private void ShowRetention(MainViewModel viewModel)
    {
        var grid = new DataGrid { ItemsSource = viewModel.RetentionItems, AutoGenerateColumns = false, MinHeight = 280 }; grid.Columns.Add(new DataGridCheckBoxColumn { Header = "Применить", Binding = new System.Windows.Data.Binding("Selected") { Mode = System.Windows.Data.BindingMode.TwoWay } }); grid.Columns.Add(new DataGridTextColumn { Header = "Действие", Binding = new System.Windows.Data.Binding("Action") }); grid.Columns.Add(new DataGridTextColumn { Header = "Причина", Binding = new System.Windows.Data.Binding("Reason") }); grid.Columns.Add(new DataGridTextColumn { Header = "Файл", Binding = new System.Windows.Data.Binding("Installer.FileName") }); grid.Columns.Add(new DataGridTextColumn { Header = "Версия", Binding = new System.Windows.Data.Binding("Installer.ProductVersion") }); grid.Columns.Add(new DataGridTextColumn { Header = "Размер", Binding = new System.Windows.Data.Binding("Installer.Size") });
        var apply = new Button { Content = "Применить выбранное", Command = viewModel.ApplyRetentionCommand }; var recalculate = new Button { Content = "Пересчитать", Margin = new Thickness(8, 0, 0, 0), Command = viewModel.RetentionPreviewCommand }; var keep = new TextBox { Width = 48, Margin = new Thickness(8, 0, 0, 0) }; keep.SetBinding(TextBox.TextProperty, new System.Windows.Data.Binding(nameof(MainViewModel.RetentionKeepLatestVersions)) { Mode = System.Windows.Data.BindingMode.TwoWay, UpdateSourceTrigger = System.Windows.Data.UpdateSourceTrigger.PropertyChanged }); var controls = new StackPanel { Orientation = Orientation.Horizontal }; controls.Children.Add(new TextBlock { Text = "Хранить последние N версий:", VerticalAlignment = VerticalAlignment.Center }); controls.Children.Add(keep); controls.Children.Add(recalculate); controls.Children.Add(apply); var panel = new DockPanel { Margin = new Thickness(12) }; DockPanel.SetDock(controls,Dock.Bottom); controls.Margin = new Thickness(0,8,0,0); panel.Children.Add(controls); panel.Children.Add(grid); new Window { Title = "Анализ архива", Content = panel, Owner = this, Width = 900, Height = 500 }.ShowDialog();
    }
    private void ShowArchiveHistory(MainViewModel viewModel)
    {
        var grid = new DataGrid { ItemsSource = viewModel.ArchiveHistoryRows, AutoGenerateColumns = false, IsReadOnly = true, MinHeight = 300 }; grid.Columns.Add(new DataGridTextColumn { Header = "Операция", Binding = new System.Windows.Data.Binding("OperationType") }); grid.Columns.Add(new DataGridTextColumn { Header = "Продукт", Binding = new System.Windows.Data.Binding("Product") }); grid.Columns.Add(new DataGridTextColumn { Header = "Файл", Binding = new System.Windows.Data.Binding("File") }); grid.Columns.Add(new DataGridTextColumn { Header = "Из", Binding = new System.Windows.Data.Binding("FromState") }); grid.Columns.Add(new DataGridTextColumn { Header = "В", Binding = new System.Windows.Data.Binding("ToState") }); grid.Columns.Add(new DataGridTextColumn { Header = "Статус", Binding = new System.Windows.Data.Binding("Status") }); grid.Columns.Add(new DataGridTextColumn { Header = "Начато", Binding = new System.Windows.Data.Binding("StartedUtc") }); grid.Columns.Add(new DataGridTextColumn { Header = "Завершено", Binding = new System.Windows.Data.Binding("CompletedUtc") }); grid.Columns.Add(new DataGridTextColumn { Header = "Ошибка", Binding = new System.Windows.Data.Binding("Error") }); new Window { Title = "История архива", Content = grid, Owner = this, Width = 1100, Height = 460 }.ShowDialog();
    }
    private static GroupBox? FindGroup(DependencyObject node, string header)
    {
        if (node is GroupBox box && Equals(box.Header, header)) return box;
        for (var i = 0; i < System.Windows.Media.VisualTreeHelper.GetChildrenCount(node); i++) { var found = FindGroup(System.Windows.Media.VisualTreeHelper.GetChild(node, i), header); if (found is not null) return found; }
        return null;
    }
}
