<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SoftwareCatalog.Core\SoftwareCatalog.Core.csproj" />
    <ProjectReference Include="..\SoftwareCatalog.Scanner\SoftwareCatalog.Scanner.csproj" />
    <ProjectReference Include="..\SoftwareCatalog.Database\SoftwareCatalog.Database.csproj" />
    <ProjectReference Include="..\SoftwareCatalog.Providers\SoftwareCatalog.Providers.csproj" />
    <ProjectReference Include="..\SoftwareCatalog.Infrastructure\SoftwareCatalog.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
  </ItemGroup>

</Project>
