using SoftwareCatalog.Core;
using SoftwareCatalog.Core.Abstractions;
using SoftwareCatalog.Core.Domain;

namespace SoftwareCatalog.Core.Tests;
public sealed class ProductCatalogServiceTests
{
    [Fact]
    public async Task GroupsNewInstallersInOnePassAndUsesLatestVersion()
    {
        var repo = new Repo(); var now = DateTimeOffset.UtcNow; repo.Files.AddRange([File(1, "1.2", now), File(2, "1.10", now)]); var service = new ProductCatalogService(repo, repo, new ProductNormalizer(), new ProductMatchingService(new ProductNormalizer()), new VersionComparer()); await service.RegroupAsync(CancellationToken.None);
        Assert.Single(repo.Products); Assert.Equal(repo.Files[0].ProductId, repo.Files[1].ProductId); Assert.Equal(ProductMatchSource.NameAndPublisher, repo.Files[1].ProductMatchSource); Assert.Equal(ProductMatchConfidence.Medium, repo.Files[1].ProductMatchConfidence); Assert.Equal("1.10", repo.Products.Single().LatestLocalVersion);
    }
    [Fact]
    public async Task PreservesManualLink() { var repo = new Repo(); var now = DateTimeOffset.UtcNow; var id = Guid.NewGuid(); repo.Products.Add(new SoftwareProduct(id, "Manual", "Publisher", "manual", now, now)); repo.Files.Add(File(1, "1.0", now) with { ProductId = id, ProductMatchSource = ProductMatchSource.Manual, ProductMatchConfidence = ProductMatchConfidence.High }); await new ProductCatalogService(repo, repo, new ProductNormalizer(), new ProductMatchingService(new ProductNormalizer()), new VersionComparer()).RegroupAsync(CancellationToken.None); Assert.Equal(ProductMatchSource.Manual, repo.Files[0].ProductMatchSource); Assert.Equal(id, repo.Files[0].ProductId); }
    [Fact]
    public async Task RepeatRegroupKeepsProductIdentityCountVersionAndBindings() { var repo = new Repo(); var now = DateTimeOffset.UtcNow; repo.Files.AddRange([File(1, "3.0", now), File(2, "25", now), File(3, "26", now)]); var service = new ProductCatalogService(repo, repo, new ProductNormalizer(), new ProductMatchingService(new ProductNormalizer()), new VersionComparer()); await service.RegroupAsync(CancellationToken.None); var first = Assert.Single(repo.Products); repo.Sources.Add(new ProductUpdateSource(Guid.NewGuid(), first.Id, "WinGet", "Vendor.Tool", true, false)); await service.RegroupAsync(CancellationToken.None); var product = Assert.Single(repo.Products); Assert.Equal(first.Id, product.Id); Assert.Equal(3, repo.Files.Count(file => file.ProductId == product.Id)); Assert.Equal("26", product.LatestLocalVersion); Assert.Single(repo.Sources, source => source.ProductId == product.Id); }
    private static InstallerFile File(long id, string version, DateTimeOffset now) => new(id, 1, $"Tool-{version}.exe", $"Tool-{version}.exe", ".exe", 1, now, null, now, now, true, ProductName: "Tool", ProductVersion: version, Publisher: "Same Publisher", NormalizedVersion: version);
    private sealed class Repo : IScanCatalogRepository, IProductCatalogRepository
    { public List<InstallerFile> Files { get; } = []; public List<SoftwareProduct> Products { get; } = []; public List<ProductUpdateSource> Sources { get; } = []; public Task<IReadOnlyList<ScanRoot>> GetScanRootsAsync(CancellationToken t) => Task.FromResult<IReadOnlyList<ScanRoot>>([]); public Task<ScanRoot> AddScanRootAsync(string s, ScanRootPathKind k, bool b, CancellationToken t) => throw new NotSupportedException(); public Task UpdateScanRootAsync(long i,string s,ScanRootPathKind k,CancellationToken t)=>Task.CompletedTask; public Task RemoveScanRootAsync(long i,CancellationToken t)=>Task.CompletedTask; public Task<InstallerFile?> FindInstallerAsync(long i,string s,CancellationToken t)=>Task.FromResult<InstallerFile?>(null); public Task UpsertInstallersAsync(IReadOnlyList<InstallerFile> f,CancellationToken t)=>Task.CompletedTask; public Task MarkMissingAsync(long i,DateTimeOffset d,CancellationToken t)=>Task.CompletedTask; public Task<IReadOnlyList<InstallerFile>> GetInstallersAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<InstallerFile>>(Files.ToArray()); public Task<IReadOnlyList<SoftwareProduct>> GetProductsAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<SoftwareProduct>>(Products.ToArray()); public Task<IReadOnlyList<InstallerFile>> GetInstallersForProductAsync(Guid p,CancellationToken t)=>Task.FromResult<IReadOnlyList<InstallerFile>>(Files.Where(f=>f.ProductId==p).ToArray()); public Task<SoftwareProduct> UpsertProductAsync(SoftwareProduct p,CancellationToken t){var index=Products.FindIndex(x=>x.Id==p.Id);if(index<0)Products.Add(p);else Products[index]=p;return Task.FromResult(p);} public Task LinkInstallerAsync(long i,Guid p,ProductMatchSource s,ProductMatchConfidence c,CancellationToken t){var index=Files.FindIndex(f=>f.Id==i);Files[index]=Files[index] with {ProductId=p,ProductMatchSource=s,ProductMatchConfidence=c};return Task.CompletedTask;} public Task<IReadOnlyList<ProductUpdateSource>> GetUpdateSourcesAsync(Guid p,CancellationToken t)=>Task.FromResult<IReadOnlyList<ProductUpdateSource>>(Sources.Where(source => source.ProductId == p).ToArray()); public Task SetUpdateSourceAsync(ProductUpdateSource s,CancellationToken t){ Sources.Add(s); return Task.CompletedTask; } public Task ClearUpdateSourcesAsync(Guid p,string s,CancellationToken t)=>Task.CompletedTask; public Task SaveUpdateCheckAsync(Guid p,UpdateCheckResult r,CancellationToken t)=>Task.CompletedTask; }
}
