using SoftwareCatalog.Core.Abstractions;
using SoftwareCatalog.Core.Domain;

namespace SoftwareCatalog.Core.Tests;

public sealed class UpdateDownloadDiscoveryServiceTests
{
    [Fact] public async Task SelectsExactKnownProductArchitecture() { var repo = new Repo("x64"); var result = await new UpdateDownloadDiscoveryService(repo, [new Provider(Candidates("x86", "x64"))]).ResolveAsync(Product(), null, CancellationToken.None); Assert.Equal(DownloadCandidateStatus.Available, result.Status); Assert.Equal("x64", Assert.Single(result.Candidates).Architecture); }
    [Fact] public async Task FallsBackToNeutralAndRejectsMultipleUnknownCandidates() { var neutral = await new UpdateDownloadDiscoveryService(new Repo("x86"), [new Provider(Candidates("x64", "neutral"))]).ResolveAsync(Product(), null, CancellationToken.None); Assert.Equal("neutral", Assert.Single(neutral.Candidates).Architecture); var ambiguous = await new UpdateDownloadDiscoveryService(new Repo((string?)null), [new Provider(Candidates("x86", "x64"))]).ResolveAsync(Product(), null, CancellationToken.None); Assert.Equal(DownloadCandidateStatus.Ambiguous, ambiguous.Status); }
    [Theory]
    [InlineData("x86")]
    [InlineData("arm64")]
    public async Task SelectsExactArchitectureForAllSupportedPlatforms(string architecture) { var result = await new UpdateDownloadDiscoveryService(new Repo(architecture), [new Provider(Candidates("x86", "x64", "arm64"))]).ResolveAsync(Product(), null, CancellationToken.None); Assert.Equal(DownloadCandidateStatus.Available, result.Status); Assert.Equal(architecture, Assert.Single(result.Candidates).Architecture); }
    [Fact] public async Task RejectsUnsupportedAndMixedLocalArchitectures() { var unsupported = await new UpdateDownloadDiscoveryService(new Repo("arm64"), [new Provider(Candidates("x64"))]).ResolveAsync(Product(), null, CancellationToken.None); Assert.Equal(DownloadCandidateStatus.Unsupported, unsupported.Status); var mixed = await new UpdateDownloadDiscoveryService(new Repo("x86", "x64"), [new Provider(Candidates("x86", "x64"))]).ResolveAsync(Product(), null, CancellationToken.None); Assert.Equal(DownloadCandidateStatus.Ambiguous, mixed.Status); }
    [Fact] public async Task ConvertsProviderFailureToErrorAndPropagatesCancellation() { var failure = await new UpdateDownloadDiscoveryService(new Repo("x64"), [new ThrowingProvider(false)]).ResolveAsync(Product(), null, CancellationToken.None); Assert.Equal(DownloadCandidateStatus.Error, failure.Status); using var cancellation = new CancellationTokenSource(); cancellation.Cancel(); await Assert.ThrowsAnyAsync<OperationCanceledException>(() => new UpdateDownloadDiscoveryService(new Repo("x64"), [new ThrowingProvider(true)]).ResolveAsync(Product(), null, cancellation.Token)); }
    private static SoftwareProduct Product() { var now = DateTimeOffset.UtcNow; return new(Guid.Parse("11111111-1111-1111-1111-111111111111"), "Tool", null, "tool", now, now); }
    private static IReadOnlyList<DownloadCandidate> Candidates(params string[] architecture) => architecture.Select(x => new DownloadCandidate("Test", "id", "2", "2", $"tool-{x}.exe", new Uri($"https://example.test/{x}.exe"), Architecture: x)).ToArray();
    private sealed class Provider(IReadOnlyList<DownloadCandidate> candidates) : IUpdateDownloadProvider { public string Id => "Test"; public bool CanHandle(SoftwareProduct p, ProductUpdateSource s) => true; public Task<DownloadCandidateResolution> ResolveAsync(SoftwareProduct p, ProductUpdateSource s, UpdateCheckResult? u, CancellationToken t) => Task.FromResult(new DownloadCandidateResolution(DownloadCandidateStatus.Ambiguous, candidates)); }
    private sealed class ThrowingProvider(bool cancellation) : IUpdateDownloadProvider { public string Id => "Throwing"; public bool CanHandle(SoftwareProduct p, ProductUpdateSource s) => true; public Task<DownloadCandidateResolution> ResolveAsync(SoftwareProduct p, ProductUpdateSource s, UpdateCheckResult? u, CancellationToken t) { if (cancellation) t.ThrowIfCancellationRequested(); throw new InvalidOperationException("provider failure"); } }
    private sealed class Repo(params string?[] architectures) : IProductCatalogRepository { public Task<IReadOnlyList<InstallerFile>> GetInstallersForProductAsync(Guid id, CancellationToken t) { var n = DateTimeOffset.UtcNow; return Task.FromResult<IReadOnlyList<InstallerFile>>(architectures.Where(x => x is not null).Select((architecture, index) => new InstallerFile(index + 1, 1, "tool.exe", "tool.exe", ".exe", 1, n, null, n, n, true, Architecture: architecture)).ToArray()); } public Task<IReadOnlyList<ProductUpdateSource>> GetUpdateSourcesAsync(Guid id, CancellationToken t) => Task.FromResult<IReadOnlyList<ProductUpdateSource>>([new(Guid.NewGuid(), id, "Test", "id")]); public Task<IReadOnlyList<SoftwareProduct>> GetProductsAsync(CancellationToken t) => Task.FromResult<IReadOnlyList<SoftwareProduct>>([]); public Task<SoftwareProduct> UpsertProductAsync(SoftwareProduct p, CancellationToken t) => Task.FromResult(p); public Task LinkInstallerAsync(long i, Guid p, ProductMatchSource s, ProductMatchConfidence c, CancellationToken t) => Task.CompletedTask; public Task SetUpdateSourceAsync(ProductUpdateSource s, CancellationToken t) => Task.CompletedTask; public Task ClearUpdateSourcesAsync(Guid p, string t, CancellationToken c) => Task.CompletedTask; public Task SaveUpdateCheckAsync(Guid p, UpdateCheckResult r, CancellationToken t) => Task.CompletedTask; }
}
