using SoftwareCatalog.Core;
using SoftwareCatalog.Core.Abstractions;
using SoftwareCatalog.Core.Domain;

namespace SoftwareCatalog.Core.Tests;

public sealed class UpdateCandidateDiscoveryServiceTests
{
    [Fact] public async Task CombinesProvidersInDeterministicOrderAndPassesAliases() { var repo=new Repo(); var product=Product(); repo.Aliases.Add(new(product.Id,"Old Tool","oldtool")); var b=new CandidateProvider("GitHub",[new("GitHub","z/repo","Z",null,null,MappingConfidence.High,"z")]); var a=new CandidateProvider("WinGet",[new("WinGet","A.Tool","A",null,null,MappingConfidence.Exact,"a")]); var result=await new UpdateCandidateDiscoveryService(repo,[b,a]).SearchAsync(product,true,12,CancellationToken.None); Assert.Equal(["WinGet","GitHub"],result.Select(x=>x.ProviderType)); Assert.Single(a.ReceivedAliases); Assert.Single(b.ReceivedAliases); }
    [Fact] public async Task FreshPositiveAndNegativeCacheSkipProvidersUnlessForced() { var repo=new Repo { Fresh=true }; var product=Product(); repo.Cached=[new("WinGet","A.Tool","A",null,null,MappingConfidence.High,"cache")]; var provider=new CandidateProvider("WinGet",[]); var service=new UpdateCandidateDiscoveryService(repo,[provider]); var positive=await service.SearchAsync(product,false,12,CancellationToken.None); Assert.Single(positive); Assert.Equal(0,provider.Calls); repo.Cached=[]; var negative=await service.SearchAsync(product,false,12,CancellationToken.None); Assert.Empty(negative); Assert.Equal(0,provider.Calls); await service.SearchAsync(product,true,12,CancellationToken.None); Assert.Equal(1,provider.Calls); }
    [Fact] public async Task ProviderFailureIsolatedAndCancellationPropagates() { var repo=new Repo(); var product=Product(); var good=new CandidateProvider("WinGet",[new("WinGet","A.Tool","A",null,null,MappingConfidence.High,"ok")]); var bad=new CandidateProvider("GitHub",[],throwFailure:true); var result=await new UpdateCandidateDiscoveryService(repo,[bad,good]).SearchAsync(product,true,12,CancellationToken.None); Assert.Single(result); using var cts=new CancellationTokenSource(); cts.Cancel(); await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>new UpdateCandidateDiscoveryService(repo,[new CandidateProvider("WinGet",[],cancel:true)]).SearchAsync(product,true,12,cts.Token)); }
    private static SoftwareProduct Product(){var now=DateTimeOffset.UtcNow;return new(Guid.NewGuid(),"Tool","Vendor","tool",now,now);}
    private sealed class CandidateProvider(string id,IReadOnlyList<UpdateCandidate> candidates,bool throwFailure=false,bool cancel=false):IUpdateProvider,IUpdateCandidateProvider { public int Calls; public List<ProductAlias> ReceivedAliases=[]; public string Id=>id; public bool CanHandle(SoftwareProduct p,ProductUpdateSource? s)=>false; public Task<UpdateCheckResult> CheckLatestAsync(SoftwareProduct p,ProductUpdateSource? s,CancellationToken t)=>Task.FromResult(new UpdateCheckResult(UpdateStatus.NotFound)); public Task<IReadOnlyList<UpdateCandidate>> SearchCandidatesAsync(SoftwareProduct p,IReadOnlyList<ProductAlias> aliases,CancellationToken t){Calls++;ReceivedAliases.AddRange(aliases);if(cancel)return Task.FromCanceled<IReadOnlyList<UpdateCandidate>>(t);if(throwFailure)return Task.FromException<IReadOnlyList<UpdateCandidate>>(new InvalidOperationException());return Task.FromResult(candidates);} }
    private sealed class Repo:IProductCatalogRepository { public bool Fresh; public List<ProductAlias> Aliases=[]; public IReadOnlyList<UpdateCandidate> Cached=[]; public Task<IReadOnlyList<SoftwareProduct>> GetProductsAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<SoftwareProduct>>([]); public Task<IReadOnlyList<InstallerFile>> GetInstallersForProductAsync(Guid p,CancellationToken t)=>Task.FromResult<IReadOnlyList<InstallerFile>>([]); public Task<SoftwareProduct> UpsertProductAsync(SoftwareProduct p,CancellationToken t)=>Task.FromResult(p); public Task LinkInstallerAsync(long i,Guid p,ProductMatchSource s,ProductMatchConfidence c,CancellationToken t)=>Task.CompletedTask; public Task<IReadOnlyList<ProductUpdateSource>> GetUpdateSourcesAsync(Guid p,CancellationToken t)=>Task.FromResult<IReadOnlyList<ProductUpdateSource>>([]); public Task SetUpdateSourceAsync(ProductUpdateSource s,CancellationToken t)=>Task.CompletedTask; public Task ClearUpdateSourcesAsync(Guid p,string s,CancellationToken t)=>Task.CompletedTask; public Task SaveUpdateCheckAsync(Guid p,UpdateCheckResult r,CancellationToken t)=>Task.CompletedTask; public Task<IReadOnlyList<ProductAlias>> GetProductAliasesAsync(Guid p,CancellationToken t)=>Task.FromResult<IReadOnlyList<ProductAlias>>(Aliases); public Task<bool> IsUpdateCandidateCacheFreshAsync(Guid p,int h,CancellationToken t)=>Task.FromResult(Fresh); public Task<IReadOnlyList<UpdateCandidate>> SearchUpdateCandidatesAsync(Guid p,bool f,int h,CancellationToken t)=>Task.FromResult(Cached); public Task SaveUpdateCandidatesAsync(Guid p,IReadOnlyList<UpdateCandidate> c,DateTimeOffset u,CancellationToken t){Cached=c;Fresh=true;return Task.CompletedTask;} }
}
