using SoftwareCatalog.Core.Domain;
using SoftwareCatalog.Database;
using Microsoft.Data.Sqlite;
using SoftwareCatalog.Database.Migrations;
using SoftwareCatalog.Infrastructure.Paths;

namespace SoftwareCatalog.Database.Tests;
public sealed class CatalogDatabaseTests : IAsyncLifetime
{
    private readonly string _folder = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));
    private CatalogDatabase _database = null!;
    public async Task InitializeAsync() { Directory.CreateDirectory(_folder); _database = new CatalogDatabase(Path.Combine(_folder, "catalog.db")); await _database.InitializeAsync(CancellationToken.None); }
    public Task DisposeAsync() { Directory.Delete(_folder, true); return Task.CompletedTask; }
    [Fact] public async Task PersistsRootAndInstallerAndMarksMissing()
    {
        var root = await _database.AddScanRootAsync("..\\Software", ScanRootPathKind.RelativeToApplication, true, CancellationToken.None);
        var now = DateTimeOffset.UtcNow; await _database.UpsertInstallersAsync([new(0, root.Id, "tool.exe", "tool.exe", ".exe", 1, now, "A", now, now, true)], CancellationToken.None);
        Assert.Single(await _database.GetInstallersAsync(CancellationToken.None)); await _database.MarkMissingAsync(root.Id, now.AddSeconds(1), CancellationToken.None);
        Assert.False((await _database.GetInstallersAsync(CancellationToken.None)).Single().Exists);
    }
    [Fact] public async Task CaseOnlyPathIsUpdatedInsteadOfDuplicated()
    {
        var root = await _database.AddScanRootAsync("C:\\Software", ScanRootPathKind.Absolute, true, CancellationToken.None); var now = DateTimeOffset.UtcNow;
        await _database.UpsertInstallersAsync([new(0, root.Id, "Tool.EXE", "Tool.EXE", ".exe", 1, now, "A", now, now, true)], CancellationToken.None);
        await _database.UpsertInstallersAsync([new(0, root.Id, "tool.exe", "tool.exe", ".exe", 2, now, "B", now, now, true)], CancellationToken.None);
        var file = (await _database.GetInstallersAsync(CancellationToken.None)).Single(); Assert.Equal(2, file.Size); Assert.Equal("B", file.Sha256);
    }
    [Fact] public async Task MigrationAndConstraintsAreEnforced()
    {
        await using var connection = new SqliteConnection($"Data Source={Path.Combine(_folder, "catalog.db")};Pooling=False"); await connection.OpenAsync();
        await using (var pragma = connection.CreateCommand()) { pragma.CommandText = "PRAGMA foreign_keys=ON"; await pragma.ExecuteNonQueryAsync(); }
        await using (var migration = connection.CreateCommand()) { migration.CommandText = "SELECT MAX(version) FROM schema_migrations"; Assert.Equal(5L, Convert.ToInt64(await migration.ExecuteScalarAsync())); }
        await using (var foreignKey = connection.CreateCommand()) { foreignKey.CommandText = "INSERT INTO installer_files(scan_root_id,relative_path,file_name,extension,size,last_write_utc,first_seen_utc,last_seen_utc,exists_flag) VALUES(999,'orphan.exe','orphan.exe','.exe',1,'2026-01-01','2026-01-01','2026-01-01',1)"; await Assert.ThrowsAsync<SqliteException>(() => foreignKey.ExecuteNonQueryAsync()); }
        var root = await _database.AddScanRootAsync("C:\\Unique", ScanRootPathKind.Absolute, true, CancellationToken.None); var now = DateTimeOffset.UtcNow;
        await _database.UpsertInstallersAsync([new(0, root.Id, "duplicate.exe", "duplicate.exe", ".exe", 1, now, null, now, now, true)], CancellationToken.None);
        await _database.UpsertInstallersAsync([new(0, root.Id, "DUPLICATE.EXE", "DUPLICATE.EXE", ".exe", 2, now, null, now, now, true)], CancellationToken.None);
        Assert.Single(await _database.GetInstallersAsync(CancellationToken.None), file => file.ScanRootId == root.Id);
    }
    [Fact] public async Task DirectCaseOnlyInsertViolatesUniqueConstraint()
    {
        var root = await _database.AddScanRootAsync("C:\\Direct", ScanRootPathKind.Absolute, true, CancellationToken.None); await using var connection = new SqliteConnection($"Data Source={Path.Combine(_folder, "catalog.db")};Pooling=False"); await connection.OpenAsync();
        await using (var first = connection.CreateCommand()) { first.CommandText = $"INSERT INTO installer_files(scan_root_id,relative_path,file_name,extension,size,last_write_utc,first_seen_utc,last_seen_utc,exists_flag) VALUES({root.Id},'Tool.exe','Tool.exe','.exe',1,'2026','2026','2026',1)"; await first.ExecuteNonQueryAsync(); }
        await using var second = connection.CreateCommand(); second.CommandText = $"INSERT INTO installer_files(scan_root_id,relative_path,file_name,extension,size,last_write_utc,first_seen_utc,last_seen_utc,exists_flag) VALUES({root.Id},'tool.EXE','tool.EXE','.exe',1,'2026','2026','2026',1)"; await Assert.ThrowsAsync<SqliteException>(() => second.ExecuteNonQueryAsync());
    }
    [Fact] public async Task InitializerUpgradesRealVersionOneDatabaseToVersionTwo()
    {
        var path = Path.Combine(_folder, "v1.db"); const string timestamp = "2026-01-01T00:00:00.0000000+00:00";
        await using (var connection = new SqliteConnection($"Data Source={path};Pooling=False")) { await connection.OpenAsync(); await using var command = connection.CreateCommand(); command.CommandText = """CREATE TABLE schema_migrations (version INTEGER PRIMARY KEY, applied_utc TEXT NOT NULL); INSERT INTO schema_migrations VALUES(1,'2026-01-01T00:00:00.0000000+00:00'); CREATE TABLE scan_roots (id INTEGER PRIMARY KEY, stored_path TEXT NOT NULL, path_kind INTEGER NOT NULL, include_subdirectories INTEGER NOT NULL, enabled INTEGER NOT NULL, created_utc TEXT NOT NULL, updated_utc TEXT NOT NULL); CREATE TABLE installer_files (id INTEGER PRIMARY KEY, scan_root_id INTEGER NOT NULL, relative_path TEXT NOT NULL, file_name TEXT NOT NULL, extension TEXT NOT NULL, size INTEGER NOT NULL, last_write_utc TEXT NOT NULL, sha256 TEXT, first_seen_utc TEXT NOT NULL, last_seen_utc TEXT NOT NULL, exists_flag INTEGER NOT NULL, FOREIGN KEY(scan_root_id) REFERENCES scan_roots(id) ON DELETE CASCADE, UNIQUE(scan_root_id, relative_path)); CREATE INDEX ix_installer_files_scan_root ON installer_files(scan_root_id); CREATE INDEX ix_installer_files_last_seen ON installer_files(last_seen_utc); CREATE INDEX ix_installer_files_exists ON installer_files(exists_flag);"""; await command.ExecuteNonQueryAsync(); command.CommandText = "INSERT INTO scan_roots VALUES(1,'C:\\Software',0,1,1,$timestamp,$timestamp); INSERT INTO installer_files VALUES(1,1,'Tool.EXE','Tool.EXE','.exe',1,$timestamp,NULL,$timestamp,$timestamp,1);"; command.Parameters.AddWithValue("$timestamp", timestamp); await command.ExecuteNonQueryAsync(); }
        var upgraded = new CatalogDatabase(path); await upgraded.InitializeAsync(CancellationToken.None); var files = await upgraded.GetInstallersAsync(CancellationToken.None); var file = Assert.Single(files); Assert.Equal(1, file.Id); Assert.Equal(1, file.ScanRootId); Assert.Equal("Tool.EXE", file.FileName); Assert.True(file.Exists); await upgraded.UpsertInstallersAsync([file with { RelativePath = "tool.exe", Size = 2 }], CancellationToken.None); Assert.Single(await upgraded.GetInstallersAsync(CancellationToken.None)); await using var check = new SqliteConnection($"Data Source={path};Pooling=False"); await check.OpenAsync(); await using var checkCommand = check.CreateCommand(); checkCommand.CommandText = "SELECT group_concat(version, ',') FROM schema_migrations ORDER BY version"; Assert.Equal("1,2,3,4,5", await checkCommand.ExecuteScalarAsync());
    }
    [Fact] public async Task FailingMigrationRollsBackAndPreservesOriginalError()
    {
        var path = Path.Combine(_folder, "rollback.db"); await using var connection = new SqliteConnection($"Data Source={path};Pooling=False"); await connection.OpenAsync(); await using (var schema = connection.CreateCommand()) { schema.CommandText = "CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY, applied_utc TEXT NOT NULL);"; await schema.ExecuteNonQueryAsync(); }
        var logger = new TestLogger(); await new MigrationRunner([new SuccessfulMigration()], logger).ApplyAsync(connection, CancellationToken.None); var exception = await Assert.ThrowsAsync<InvalidOperationException>(() => new MigrationRunner([new FailingMigration()], logger).ApplyAsync(connection, CancellationToken.None)); Assert.Equal("intentional migration failure", exception.Message); Assert.Contains(logger.Errors, message => message.Contains("Version 99") && message.Contains("intentional migration failure"));
        await using var check = connection.CreateCommand(); check.CommandText = "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='rollback_probe';"; Assert.Equal(0L, Convert.ToInt64(await check.ExecuteScalarAsync())); check.CommandText = "SELECT COUNT(*) FROM schema_migrations WHERE version=99;"; Assert.Equal(0L, Convert.ToInt64(await check.ExecuteScalarAsync())); check.CommandText = "SELECT COUNT(*) FROM schema_migrations WHERE version=98;"; Assert.Equal(1L, Convert.ToInt64(await check.ExecuteScalarAsync())); check.CommandText = "SELECT COUNT(*) FROM successful_probe;"; Assert.Equal(1L, Convert.ToInt64(await check.ExecuteScalarAsync()));
    }
    [Fact] public async Task DatabaseFailureLogsContextAndPreservesException()
    {
        var logger = new TestLogger(); var blocker = Path.Combine(_folder, "not-a-directory"); await File.WriteAllTextAsync(blocker, "x"); var database = new CatalogDatabase(Path.Combine(blocker, "catalog.db"), logger); var exception = await Assert.ThrowsAnyAsync<Exception>(() => database.GetScanRootsAsync(CancellationToken.None)); Assert.NotNull(exception); Assert.Contains(logger.Errors, message => message.Contains("GetScanRoots") && message.Contains("databasePath="));
    }
    [Fact] public async Task UpsertFailureLogsOperationContextAndPreservesException()
    {
        var logger = new TestLogger(); var database = new CatalogDatabase(Path.Combine(_folder, "logging.db"), logger); await database.InitializeAsync(CancellationToken.None); var now = DateTimeOffset.UtcNow; var exception = await Assert.ThrowsAsync<SqliteException>(() => database.UpsertInstallersAsync([new InstallerFile(0, 999, "tool.exe", "tool.exe", ".exe", 1, now, null, now, now, true)], CancellationToken.None)); Assert.NotNull(exception); Assert.Contains(logger.Errors, message => message.Contains("UpsertInstallers") && message.Contains("fileCount=1") && message.Contains("rootId=999"));
    }
    [Fact] public async Task UpdateFailureLogsOperationContextAndPreservesException()
    {
        var path = Path.Combine(_folder, "update-logging.db"); var logger = new TestLogger(); var database = new CatalogDatabase(path, logger); await database.InitializeAsync(CancellationToken.None); await using (var connection = new SqliteConnection($"Data Source={path};Pooling=False")) { await connection.OpenAsync(); await using var command = connection.CreateCommand(); command.CommandText = "DROP TABLE scan_roots"; await command.ExecuteNonQueryAsync(); } var exception = await Assert.ThrowsAsync<SqliteException>(() => database.UpdateScanRootAsync(42, "C:\\New", ScanRootPathKind.Absolute, CancellationToken.None)); Assert.NotNull(exception); Assert.Contains(logger.Errors, message => message.Contains("UpdateScanRoot") && message.Contains("rootId=42"));
    }
    [Fact] public async Task UpdatingRootPreservesIdentityAndSettings()
    {
        var oldPath = Path.Combine(_folder, "Old"); var newPath = Path.Combine(_folder, "New"); Directory.CreateDirectory(oldPath); Directory.CreateDirectory(newPath); var old = await _database.AddScanRootAsync(oldPath, ScanRootPathKind.Absolute, false, CancellationToken.None); await Task.Delay(5); await _database.UpdateScanRootAsync(old.Id, newPath, old.PathKind, CancellationToken.None); var updated = Assert.Single(await _database.GetScanRootsAsync(CancellationToken.None)); Assert.Equal(old.Id, updated.Id); Assert.Equal(old.PathKind, updated.PathKind); Assert.Equal(old.IncludeSubdirectories, updated.IncludeSubdirectories); Assert.Equal(old.Enabled, updated.Enabled); Assert.Equal(newPath, updated.StoredPath); Assert.True(updated.UpdatedUtc > old.UpdatedUtc); Assert.Equal(ScanRootAvailability.Available, new PortablePathResolver(new PortableAppPathService(_folder)).GetAvailability(updated));
    }
    [Fact] public async Task InitializerUpgradesRealVersionTwoDatabaseToVersionThreeAndIsIdempotent()
    {
        var path = Path.Combine(_folder, "v2.db"); const string timestamp = "2026-01-01T00:00:00.0000000+00:00";
        await using (var connection = new SqliteConnection($"Data Source={path};Pooling=False")) { await connection.OpenAsync(); await using var command = connection.CreateCommand(); command.CommandText = """CREATE TABLE schema_migrations (version INTEGER PRIMARY KEY, applied_utc TEXT NOT NULL); INSERT INTO schema_migrations VALUES(1,'2026-01-01T00:00:00.0000000+00:00'); INSERT INTO schema_migrations VALUES(2,'2026-01-01T00:00:00.0000000+00:00'); CREATE TABLE scan_roots (id INTEGER PRIMARY KEY, stored_path TEXT NOT NULL, path_kind INTEGER NOT NULL, include_subdirectories INTEGER NOT NULL, enabled INTEGER NOT NULL, created_utc TEXT NOT NULL, updated_utc TEXT NOT NULL); CREATE TABLE installer_files (id INTEGER PRIMARY KEY, scan_root_id INTEGER NOT NULL, relative_path TEXT NOT NULL COLLATE NOCASE, file_name TEXT NOT NULL, extension TEXT NOT NULL, size INTEGER NOT NULL, last_write_utc TEXT NOT NULL, sha256 TEXT, first_seen_utc TEXT NOT NULL, last_seen_utc TEXT NOT NULL, exists_flag INTEGER NOT NULL, FOREIGN KEY(scan_root_id) REFERENCES scan_roots(id) ON DELETE CASCADE, UNIQUE(scan_root_id, relative_path)); CREATE INDEX ix_installer_files_scan_root ON installer_files(scan_root_id); CREATE INDEX ix_installer_files_last_seen ON installer_files(last_seen_utc); CREATE INDEX ix_installer_files_exists ON installer_files(exists_flag);"""; await command.ExecuteNonQueryAsync(); command.CommandText = "INSERT INTO scan_roots VALUES(7,'C:\\Legacy',0,1,1,$timestamp,$timestamp); INSERT INTO installer_files VALUES(42,7,'nested\\Tool.EXE','Tool.EXE','.exe',123,$timestamp,'HASH',$timestamp,$timestamp,1);"; command.Parameters.AddWithValue("$timestamp", timestamp); await command.ExecuteNonQueryAsync(); }
        var database = new CatalogDatabase(path); await database.InitializeAsync(CancellationToken.None); var file = Assert.Single(await database.GetInstallersAsync(CancellationToken.None));
        Assert.Equal(42, file.Id); Assert.Equal(7, file.ScanRootId); Assert.Equal("nested\\Tool.EXE", file.RelativePath); Assert.Equal("HASH", file.Sha256); Assert.Equal(DateTimeOffset.Parse(timestamp), file.FirstSeenUtc); Assert.True(file.Exists); Assert.Equal(InstallerKind.Unknown, file.InstallerKind); Assert.Equal(MetadataStatus.NotProcessed, file.MetadataStatus); Assert.Null(file.ProductName);
        await database.InitializeAsync(CancellationToken.None); await using var check = new SqliteConnection($"Data Source={path};Pooling=False"); await check.OpenAsync(); await using var verify = check.CreateCommand(); verify.CommandText = "SELECT group_concat(version, ',') FROM schema_migrations ORDER BY version"; Assert.Equal("1,2,3,4,5", await verify.ExecuteScalarAsync()); Assert.Single(await database.GetInstallersAsync(CancellationToken.None));
    }
    [Fact] public async Task InitializerUpgradesVersionThreeDatabaseToVersionFourWithoutChangingMetadata()
    {
        var path = Path.Combine(_folder, "v3.db"); var stageThree = new CatalogDatabase(path); await stageThree.InitializeAsync(CancellationToken.None); var root = await stageThree.AddScanRootAsync("C:\\Stage3", ScanRootPathKind.Absolute, true, CancellationToken.None); var now = DateTimeOffset.UtcNow;
        await stageThree.UpsertInstallersAsync([new InstallerFile(0, root.Id, "bundle.msixbundle", "bundle.msixbundle", ".msixbundle", 8, now, "HASH", now, now, true, InstallerKind.MsixBundle, "Bundle", "1.0", "Publisher", null, null, "x86,x64", MetadataSource.MsixManifest, MetadataStatus.Success, null, "1.0", null, null, "old-package-list")], CancellationToken.None);
        await using (var connection = new SqliteConnection($"Data Source={path};Pooling=False")) { await connection.OpenAsync(); await using var command = connection.CreateCommand(); command.CommandText = "ALTER TABLE installer_files DROP COLUMN package_list; DELETE FROM schema_migrations WHERE version=4;"; await command.ExecuteNonQueryAsync(); }
        var upgraded = new CatalogDatabase(path); await upgraded.InitializeAsync(CancellationToken.None); var file = Assert.Single(await upgraded.GetInstallersAsync(CancellationToken.None));
        Assert.Equal(root.Id, file.ScanRootId); Assert.Equal("bundle.msixbundle", file.RelativePath); Assert.Equal("HASH", file.Sha256); Assert.Equal(InstallerKind.MsixBundle, file.InstallerKind); Assert.Equal("Bundle", file.ProductName); Assert.Equal("x86,x64", file.Architecture); Assert.Null(file.PackageList);
        await upgraded.UpsertInstallersAsync([file with { PackageList = "x86.msix,x64.msix" }], CancellationToken.None); Assert.Equal("x86.msix,x64.msix", (await upgraded.GetInstallersAsync(CancellationToken.None)).Single().PackageList);
        await upgraded.InitializeAsync(CancellationToken.None); await using var check = new SqliteConnection($"Data Source={path};Pooling=False"); await check.OpenAsync(); await using var verify = check.CreateCommand(); verify.CommandText = "SELECT group_concat(version, ',') FROM schema_migrations ORDER BY version"; Assert.Equal("1,2,3,4,5", await verify.ExecuteScalarAsync()); Assert.Single(await upgraded.GetInstallersAsync(CancellationToken.None));
    }
    [Fact] public async Task InitializerUpgradesManuallyCreatedVersionFourDatabaseToVersionFive()
    {
        var path = Path.Combine(_folder, "manual-v4.db");
        await using (var connection = new SqliteConnection($"Data Source={path};Pooling=False")) { await connection.OpenAsync(); await using var command = connection.CreateCommand(); command.CommandText = """
            CREATE TABLE schema_migrations (version INTEGER PRIMARY KEY, applied_utc TEXT NOT NULL);
            INSERT INTO schema_migrations VALUES(1,'2026-01-01T00:00:00.0000000+00:00'),(2,'2026-01-01T00:00:00.0000000+00:00'),(3,'2026-01-01T00:00:00.0000000+00:00'),(4,'2026-01-01T00:00:00.0000000+00:00');
            CREATE TABLE scan_roots (id INTEGER PRIMARY KEY, stored_path TEXT NOT NULL, path_kind INTEGER NOT NULL, include_subdirectories INTEGER NOT NULL, enabled INTEGER NOT NULL, created_utc TEXT NOT NULL, updated_utc TEXT NOT NULL);
            CREATE TABLE installer_files (id INTEGER PRIMARY KEY, scan_root_id INTEGER NOT NULL, relative_path TEXT NOT NULL COLLATE NOCASE, file_name TEXT NOT NULL, extension TEXT NOT NULL, size INTEGER NOT NULL, last_write_utc TEXT NOT NULL, sha256 TEXT, first_seen_utc TEXT NOT NULL, last_seen_utc TEXT NOT NULL, exists_flag INTEGER NOT NULL, installer_kind INTEGER NOT NULL DEFAULT 0, product_name TEXT, product_version TEXT, publisher TEXT, file_version TEXT, file_description TEXT, architecture TEXT, metadata_source INTEGER NOT NULL DEFAULT 0, metadata_status INTEGER NOT NULL DEFAULT 0, metadata_error TEXT, normalized_version TEXT, product_code TEXT, upgrade_code TEXT, package_list TEXT, FOREIGN KEY(scan_root_id) REFERENCES scan_roots(id) ON DELETE CASCADE, UNIQUE(scan_root_id, relative_path));
            INSERT INTO scan_roots VALUES(1,'C:\\Legacy',0,1,1,'2026-01-01T00:00:00.0000000+00:00','2026-01-01T00:00:00.0000000+00:00');
            INSERT INTO installer_files VALUES(1,1,'Tool.msix','Tool.msix','.msix',1,'2026-01-01T00:00:00.0000000+00:00',NULL,'2026-01-01T00:00:00.0000000+00:00','2026-01-01T00:00:00.0000000+00:00',1,3,'Legacy Tool','1.0','Legacy Corp',NULL,NULL,NULL,2,1,NULL,'1.0',NULL,NULL,NULL);
            """; await command.ExecuteNonQueryAsync(); }
        var database = new CatalogDatabase(path); await database.InitializeAsync(CancellationToken.None); var file = Assert.Single(await database.GetInstallersAsync(CancellationToken.None)); Assert.Equal("Legacy Tool", file.ProductName); Assert.Null(file.ProductId); Assert.Null(file.MsixIdentityName);
        await using var check = new SqliteConnection($"Data Source={path};Pooling=False"); await check.OpenAsync(); await using var verify = check.CreateCommand(); verify.CommandText = "SELECT group_concat(version, ',') FROM schema_migrations ORDER BY version"; Assert.Equal("1,2,3,4,5", await verify.ExecuteScalarAsync()); verify.CommandText = "SELECT COUNT(*) FROM pragma_table_info('installer_files') WHERE name IN ('product_id','product_match_source','product_match_confidence','msix_identity_name')"; Assert.Equal(4L, Convert.ToInt64(await verify.ExecuteScalarAsync()));
    }
    private sealed class SuccessfulMigration : IMigration { public int Version => 98; public async Task ApplyAsync(SqliteConnection connection, SqliteTransaction transaction, CancellationToken cancellationToken) { await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = "CREATE TABLE successful_probe(id INTEGER); INSERT INTO successful_probe VALUES(1);"; await command.ExecuteNonQueryAsync(cancellationToken); } }
    private sealed class FailingMigration : IMigration { public int Version => 99; public async Task ApplyAsync(SqliteConnection connection, SqliteTransaction transaction, CancellationToken cancellationToken) { await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = "CREATE TABLE rollback_probe(id INTEGER);"; await command.ExecuteNonQueryAsync(cancellationToken); throw new InvalidOperationException("intentional migration failure"); } }
    private sealed class TestLogger : SoftwareCatalog.Core.Abstractions.IAppLogger { public List<string> Errors { get; } = []; public void Information(string operation, string message) { } public void Error(string operation, string message) => Errors.Add($"{operation}: {message}"); }
}
