using Microsoft.Data.Sqlite;
using SoftwareCatalog.Core.Domain;
using SoftwareCatalog.Database;

namespace SoftwareCatalog.Database.Tests;

public sealed class Migration008ProductMappingsTests : IDisposable
{
    private readonly string _folder=Path.Combine(Path.GetTempPath(),"catalog-m8-"+Guid.NewGuid().ToString("N"));
    [Fact]
    public async Task ManualV7DatabaseUpgradesLegacyMappingsAndIsIdempotent()
    {
        Directory.CreateDirectory(_folder); var path=Path.Combine(_folder,"catalog.db"); var now="2026-01-01T00:00:00.0000000+00:00";
        await using(var c=new SqliteConnection($"Data Source={path};Pooling=False")) { await c.OpenAsync(); await using var cmd=c.CreateCommand(); cmd.CommandText=$"""
CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,applied_utc TEXT NOT NULL); INSERT INTO schema_migrations VALUES(1,'{now}'),(2,'{now}'),(3,'{now}'),(4,'{now}'),(5,'{now}'),(6,'{now}'),(7,'{now}');
CREATE TABLE scan_roots(id INTEGER PRIMARY KEY,stored_path TEXT NOT NULL,path_kind INTEGER NOT NULL,include_subdirectories INTEGER NOT NULL,enabled INTEGER NOT NULL,created_utc TEXT NOT NULL,updated_utc TEXT NOT NULL,role INTEGER NOT NULL DEFAULT 0);
CREATE TABLE installer_files(id INTEGER PRIMARY KEY,scan_root_id INTEGER NOT NULL,relative_path TEXT NOT NULL COLLATE NOCASE,file_name TEXT NOT NULL,extension TEXT NOT NULL,size INTEGER NOT NULL,last_write_utc TEXT NOT NULL,sha256 TEXT,first_seen_utc TEXT NOT NULL,last_seen_utc TEXT NOT NULL,exists_flag INTEGER NOT NULL,installer_kind INTEGER NOT NULL DEFAULT 0,product_name TEXT,product_version TEXT,publisher TEXT,file_version TEXT,file_description TEXT,architecture TEXT,metadata_source INTEGER NOT NULL DEFAULT 0,metadata_status INTEGER NOT NULL DEFAULT 0,metadata_error TEXT,normalized_version TEXT,product_code TEXT,upgrade_code TEXT,package_list TEXT,product_id TEXT,product_match_source INTEGER,product_match_confidence INTEGER,msix_identity_name TEXT,storage_state INTEGER NOT NULL DEFAULT 0,is_pinned INTEGER NOT NULL DEFAULT 0,storage_changed_utc TEXT,original_scan_root_id INTEGER,original_relative_path TEXT);
CREATE TABLE software_products(id TEXT PRIMARY KEY,canonical_name TEXT NOT NULL,publisher TEXT,normalized_name TEXT NOT NULL,created_utc TEXT NOT NULL,updated_utc TEXT NOT NULL,latest_local_version TEXT,latest_normalized_version TEXT,update_status INTEGER NOT NULL DEFAULT 0,latest_version TEXT,update_provider TEXT,external_product_id TEXT,last_checked_utc TEXT,update_error TEXT);
CREATE TABLE product_update_sources(id TEXT PRIMARY KEY,product_id TEXT NOT NULL,provider_type TEXT NOT NULL,external_id TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,is_explicit INTEGER NOT NULL DEFAULT 0,FOREIGN KEY(product_id) REFERENCES software_products(id) ON DELETE CASCADE,UNIQUE(product_id,provider_type));
CREATE TABLE download_history(id TEXT PRIMARY KEY,product_id TEXT NOT NULL,provider_type TEXT NOT NULL,external_product_id TEXT NOT NULL,version TEXT,file_name TEXT,source_url TEXT,expected_sha256 TEXT,actual_sha256 TEXT,status INTEGER NOT NULL,error TEXT,started_utc TEXT NOT NULL,completed_utc TEXT,final_relative_path TEXT);
CREATE TABLE archive_operations(id TEXT PRIMARY KEY,installer_id INTEGER NOT NULL,product_id TEXT,operation_type INTEGER NOT NULL,from_state INTEGER NOT NULL,to_state INTEGER,source_path TEXT NOT NULL,destination_path TEXT,sha256 TEXT,status INTEGER NOT NULL,error TEXT,started_utc TEXT NOT NULL,completed_utc TEXT);
INSERT INTO scan_roots VALUES(1,'C:\\Legacy',0,1,1,'{now}','{now}',0);
INSERT INTO installer_files(id,scan_root_id,relative_path,file_name,extension,size,last_write_utc,first_seen_utc,last_seen_utc,exists_flag,product_name,product_version,publisher,normalized_version,storage_state,is_pinned) VALUES(1,1,'Tool.exe','Tool.exe','.exe',42,'{now}','{now}','{now}',1,'Tool','1.0','Vendor','1.0',0,0);
INSERT INTO software_products VALUES('11111111-1111-1111-1111-111111111111','Tool','Vendor','tool','{now}','{now}','1.0','1.0',0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO product_update_sources VALUES('22222222-2222-2222-2222-222222222222','11111111-1111-1111-1111-111111111111','WinGet','Vendor.Tool',1,0);
INSERT INTO product_update_sources VALUES('55555555-5555-5555-5555-555555555555','11111111-1111-1111-1111-111111111111','GitHub','owner/repo',1,1);
INSERT INTO download_history VALUES('33333333-3333-3333-3333-333333333333','11111111-1111-1111-1111-111111111111','WinGet','Vendor.Tool','1.0','Tool.exe','https://example.test/tool.exe',NULL,NULL,0,NULL,'{now}',NULL,NULL);
INSERT INTO archive_operations VALUES('44444444-4444-4444-4444-444444444444',1,'11111111-1111-1111-1111-111111111111',0,0,NULL,'C:\\Legacy\\Tool.exe',NULL,NULL,0,NULL,'{now}',NULL);
"""; await cmd.ExecuteNonQueryAsync(); }
        var database=new CatalogDatabase(path); await database.InitializeAsync(CancellationToken.None); var productId=Guid.Parse("11111111-1111-1111-1111-111111111111"); var mappings=await database.GetUpdateSourcesAsync(productId,CancellationToken.None); var mapping=Assert.Single(mappings,x=>x.ProviderType=="WinGet"); var explicitMapping=Assert.Single(mappings,x=>x.ProviderType=="GitHub");
        Assert.Equal("Vendor.Tool",mapping.ExternalId); Assert.Equal(MappingSource.ExactMatch,mapping.Source); Assert.Equal(MappingConfidence.High,mapping.Confidence); Assert.NotNull(mapping.CreatedUtc); Assert.NotNull(mapping.UpdatedUtc); Assert.True(mapping.Enabled); Assert.False(mapping.IsExplicit);
        Assert.Equal("owner/repo",explicitMapping.ExternalId); Assert.Equal(MappingSource.Manual,explicitMapping.Source); Assert.Equal(MappingConfidence.Exact,explicitMapping.Confidence); Assert.True(explicitMapping.Enabled); Assert.True(explicitMapping.IsExplicit); Assert.NotNull(explicitMapping.CreatedUtc); Assert.NotNull(explicitMapping.UpdatedUtc);
        await database.InitializeAsync(CancellationToken.None); Assert.Equal(2,(await database.GetUpdateSourcesAsync(productId,CancellationToken.None)).Count);
        await using var verify=new SqliteConnection($"Data Source={path};Pooling=False"); await verify.OpenAsync(); await using var command=verify.CreateCommand(); command.CommandText="SELECT group_concat(version, ',') FROM (SELECT version FROM schema_migrations ORDER BY version)"; Assert.Equal("1,2,3,4,5,6,7,8",await command.ExecuteScalarAsync()); command.CommandText="SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name IN ('product_aliases','update_candidate_cache')"; Assert.Equal(2L,Convert.ToInt64(await command.ExecuteScalarAsync()));
        command.CommandText="SELECT id,stored_path,path_kind,role FROM scan_roots"; await using(var r=await command.ExecuteReaderAsync()){Assert.True(await r.ReadAsync());Assert.Equal(1L,r.GetInt64(0));Assert.Equal("C:\\\\Legacy",r.GetString(1));Assert.Equal(0,r.GetInt32(2));Assert.Equal(0,r.GetInt32(3));}
        command.CommandText="SELECT id,file_name,relative_path,size,product_name,product_version,publisher,normalized_version,storage_state,is_pinned FROM installer_files"; await using(var r=await command.ExecuteReaderAsync()){Assert.True(await r.ReadAsync());Assert.Equal(1L,r.GetInt64(0));Assert.Equal("Tool.exe",r.GetString(1));Assert.Equal("Tool.exe",r.GetString(2));Assert.Equal(42L,r.GetInt64(3));Assert.Equal("Tool",r.GetString(4));Assert.Equal("1.0",r.GetString(5));Assert.Equal("Vendor",r.GetString(6));Assert.Equal("1.0",r.GetString(7));Assert.Equal(0,r.GetInt32(8));Assert.Equal(0,r.GetInt32(9));}
        command.CommandText="SELECT id,canonical_name,publisher,latest_local_version FROM software_products"; await using(var r=await command.ExecuteReaderAsync()){Assert.True(await r.ReadAsync());Assert.Equal("11111111-1111-1111-1111-111111111111",r.GetString(0));Assert.Equal("Tool",r.GetString(1));Assert.Equal("Vendor",r.GetString(2));Assert.Equal("1.0",r.GetString(3));}
        command.CommandText="SELECT id,provider_type,external_product_id,version,file_name,source_url,status FROM download_history"; await using(var r=await command.ExecuteReaderAsync()){Assert.True(await r.ReadAsync());Assert.Equal("33333333-3333-3333-3333-333333333333",r.GetString(0));Assert.Equal("WinGet",r.GetString(1));Assert.Equal("Vendor.Tool",r.GetString(2));Assert.Equal("1.0",r.GetString(3));Assert.Equal("Tool.exe",r.GetString(4));Assert.Equal("https://example.test/tool.exe",r.GetString(5));Assert.Equal(0,r.GetInt32(6));}
        command.CommandText="SELECT id,installer_id,product_id,operation_type,from_state,status,source_path FROM archive_operations"; await using(var r=await command.ExecuteReaderAsync()){Assert.True(await r.ReadAsync());Assert.Equal("44444444-4444-4444-4444-444444444444",r.GetString(0));Assert.Equal(1L,r.GetInt64(1));Assert.Equal("11111111-1111-1111-1111-111111111111",r.GetString(2));Assert.Equal(0,r.GetInt32(3));Assert.Equal(0,r.GetInt32(4));Assert.Equal(0,r.GetInt32(5));Assert.Equal("C:\\\\Legacy\\\\Tool.exe",r.GetString(6));}
        command.CommandText="SELECT COUNT(*) FROM scan_roots"; Assert.Equal(1L,Convert.ToInt64(await command.ExecuteScalarAsync())); command.CommandText="SELECT COUNT(*) FROM installer_files"; Assert.Equal(1L,Convert.ToInt64(await command.ExecuteScalarAsync())); command.CommandText="SELECT COUNT(*) FROM download_history"; Assert.Equal(1L,Convert.ToInt64(await command.ExecuteScalarAsync())); command.CommandText="SELECT COUNT(*) FROM archive_operations"; Assert.Equal(1L,Convert.ToInt64(await command.ExecuteScalarAsync()));
    }
    public void Dispose(){if(Directory.Exists(_folder))Directory.Delete(_folder,true);}
}
