using Microsoft.Data.Sqlite;
using SoftwareCatalog.Core.Domain;
using SoftwareCatalog.Database;

namespace SoftwareCatalog.Database.Tests;

public sealed class Migration007ArchiveRetentionTests : IDisposable
{
    private readonly string _folder = Path.Combine(Path.GetTempPath(), "catalog-m7-" + Guid.NewGuid().ToString("N"));
    [Fact] public async Task RealV6FixtureUpgradesIdempotentlyAndPreservesExistingState()
    {
        Directory.CreateDirectory(_folder); var path=Path.Combine(_folder,"catalog.db"); var initial=new CatalogDatabase(path); await initial.InitializeAsync(CancellationToken.None);
        var root=await initial.AddScanRootAsync("C:\\Installers",ScanRootPathKind.Absolute,true,CancellationToken.None); var now=DateTimeOffset.UtcNow; var file=new InstallerFile(0,root.Id,"tool.exe","tool.exe",".exe",123,now,"ABC",now,now,true,ProductName:"Tool",ProductVersion:"2.0",NormalizedVersion:"2.0"); await initial.UpsertInstallersAsync([file],CancellationToken.None); var stored=Assert.Single(await initial.GetInstallersAsync(CancellationToken.None));
        await using (var c=new SqliteConnection($"Data Source={path};Pooling=False")) { await c.OpenAsync(); await using var cmd=c.CreateCommand(); cmd.CommandText="DROP TABLE archive_operations; DROP INDEX ix_installer_files_storage_state; ALTER TABLE installer_files DROP COLUMN storage_state; ALTER TABLE installer_files DROP COLUMN is_pinned; ALTER TABLE installer_files DROP COLUMN storage_changed_utc; ALTER TABLE installer_files DROP COLUMN original_scan_root_id; ALTER TABLE installer_files DROP COLUMN original_relative_path; ALTER TABLE scan_roots DROP COLUMN role; DELETE FROM schema_migrations WHERE version=7;"; await cmd.ExecuteNonQueryAsync(); }
        var upgraded=new CatalogDatabase(path); await upgraded.InitializeAsync(CancellationToken.None); await upgraded.InitializeAsync(CancellationToken.None);
        var result=Assert.Single(await upgraded.GetInstallersAsync(CancellationToken.None)); Assert.Equal(stored.Id,result.Id); Assert.Equal("ABC",result.Sha256); Assert.Equal(InstallerStorageState.Active,result.StorageState); Assert.False(result.IsPinned); Assert.Null(result.StorageChangedUtc);
        await using var verify=new SqliteConnection($"Data Source={path};Pooling=False"); await verify.OpenAsync(); await using var versions=verify.CreateCommand(); versions.CommandText="SELECT group_concat(version, ',') FROM (SELECT version FROM schema_migrations ORDER BY version)"; Assert.Equal("1,2,3,4,5,6,7",await versions.ExecuteScalarAsync()); versions.CommandText="SELECT COUNT(*) FROM archive_operations"; Assert.Equal(0L,Convert.ToInt64(await versions.ExecuteScalarAsync()));
    }
    [Fact] public async Task ManuallyCreatedV6DatabaseUpgradesToV7WithoutLosingStageOneToFourData()
    {
        Directory.CreateDirectory(_folder); var path=Path.Combine(_folder,"manual-v6.db"); var now="2026-01-01T00:00:00.0000000+00:00";
        await using (var c=new SqliteConnection($"Data Source={path};Pooling=False")) { await c.OpenAsync(); await using var cmd=c.CreateCommand(); cmd.CommandText=$"""
CREATE TABLE schema_migrations (version INTEGER PRIMARY KEY, applied_utc TEXT NOT NULL); INSERT INTO schema_migrations VALUES(1,'{now}'),(2,'{now}'),(3,'{now}'),(4,'{now}'),(5,'{now}'),(6,'{now}');
CREATE TABLE scan_roots (id INTEGER PRIMARY KEY, stored_path TEXT NOT NULL, path_kind INTEGER NOT NULL, include_subdirectories INTEGER NOT NULL, enabled INTEGER NOT NULL, created_utc TEXT NOT NULL, updated_utc TEXT NOT NULL);
CREATE TABLE installer_files (id INTEGER PRIMARY KEY, scan_root_id INTEGER NOT NULL, relative_path TEXT NOT NULL COLLATE NOCASE, file_name TEXT NOT NULL, extension TEXT NOT NULL, size INTEGER NOT NULL, last_write_utc TEXT NOT NULL, sha256 TEXT, first_seen_utc TEXT NOT NULL, last_seen_utc TEXT NOT NULL, exists_flag INTEGER NOT NULL, installer_kind INTEGER NOT NULL DEFAULT 0, product_name TEXT, product_version TEXT, publisher TEXT, file_version TEXT, file_description TEXT, architecture TEXT, metadata_source INTEGER NOT NULL DEFAULT 0, metadata_status INTEGER NOT NULL DEFAULT 0, metadata_error TEXT, normalized_version TEXT, product_code TEXT, upgrade_code TEXT, package_list TEXT, product_id TEXT REFERENCES software_products(id) ON DELETE SET NULL, product_match_source INTEGER, product_match_confidence INTEGER, msix_identity_name TEXT, FOREIGN KEY(scan_root_id) REFERENCES scan_roots(id) ON DELETE CASCADE, UNIQUE(scan_root_id, relative_path));
CREATE TABLE software_products (id TEXT PRIMARY KEY, canonical_name TEXT NOT NULL, publisher TEXT, normalized_name TEXT NOT NULL, created_utc TEXT NOT NULL, updated_utc TEXT NOT NULL, latest_local_version TEXT, latest_normalized_version TEXT, update_status INTEGER NOT NULL DEFAULT 0, latest_version TEXT, update_provider TEXT, external_product_id TEXT, last_checked_utc TEXT, update_error TEXT);
CREATE TABLE product_update_sources (id TEXT PRIMARY KEY, product_id TEXT NOT NULL, provider_type TEXT NOT NULL, external_id TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, is_explicit INTEGER NOT NULL DEFAULT 0, FOREIGN KEY(product_id) REFERENCES software_products(id) ON DELETE CASCADE, UNIQUE(product_id, provider_type));
CREATE TABLE download_history (id TEXT PRIMARY KEY, product_id TEXT NOT NULL, provider_type TEXT NOT NULL, external_product_id TEXT NOT NULL, version TEXT, file_name TEXT, source_url TEXT, expected_sha256 TEXT, actual_sha256 TEXT, status INTEGER NOT NULL, error TEXT, started_utc TEXT NOT NULL, completed_utc TEXT, final_relative_path TEXT);
CREATE INDEX ix_installer_files_scan_root ON installer_files(scan_root_id); CREATE INDEX ix_installer_files_last_seen ON installer_files(last_seen_utc); CREATE INDEX ix_installer_files_exists ON installer_files(exists_flag); CREATE INDEX ix_installer_files_product ON installer_files(product_id); CREATE UNIQUE INDEX ix_software_products_name_publisher ON software_products(normalized_name, publisher); CREATE INDEX ix_download_history_product ON download_history(product_id);
INSERT INTO scan_roots VALUES(1,'C:\\Installers',0,1,1,'{now}','{now}'); INSERT INTO software_products VALUES('11111111-1111-1111-1111-111111111111','Tool','Vendor','tool','{now}','{now}','2.0','2.0',1,'3.0','WinGet','Vendor.Tool','{now}',NULL); INSERT INTO installer_files VALUES(7,1,'tool.exe','tool.exe','.exe',123,'{now}','ABC','{now}','{now}',1,1,'Tool','2.0','Vendor','2.0','Tool installer','x64',1,1,NULL,'2.0','pc','uc','x64', '11111111-1111-1111-1111-111111111111',1,2,'tool'); INSERT INTO product_update_sources VALUES('22222222-2222-2222-2222-222222222222','11111111-1111-1111-1111-111111111111','WinGet','Vendor.Tool',1,1); INSERT INTO download_history VALUES('33333333-3333-3333-3333-333333333333','11111111-1111-1111-1111-111111111111','WinGet','Vendor.Tool','3.0','tool.exe','https://example.invalid/tool.exe','E','A',5,NULL,'{now}','{now}','Downloads/tool.exe');
"""; await cmd.ExecuteNonQueryAsync(); }
        var db=new CatalogDatabase(path); await db.InitializeAsync(CancellationToken.None); await db.InitializeAsync(CancellationToken.None); var file=Assert.Single(await db.GetInstallersAsync(CancellationToken.None)); Assert.Equal(7,file.Id); Assert.Equal("ABC",file.Sha256); Assert.Equal("Tool",file.ProductName); Assert.Equal(InstallerStorageState.Active,file.StorageState); Assert.False(file.IsPinned); Assert.Null(file.StorageChangedUtc); Assert.Null(file.OriginalScanRootId); Assert.Null(file.OriginalRelativePath); var root=Assert.Single(await db.GetScanRootsAsync(CancellationToken.None)); Assert.Equal(ScanRootRole.User,root.Role);
        await using var verify=new SqliteConnection($"Data Source={path};Pooling=False"); await verify.OpenAsync(); await using var command=verify.CreateCommand(); command.CommandText="SELECT group_concat(version, ',') FROM (SELECT version FROM schema_migrations ORDER BY version)"; Assert.Equal("1,2,3,4,5,6,7",await command.ExecuteScalarAsync()); command.CommandText="SELECT COUNT(*) FROM archive_operations"; Assert.Equal(0L,Convert.ToInt64(await command.ExecuteScalarAsync())); command.CommandText="SELECT external_id FROM product_update_sources"; Assert.Equal("Vendor.Tool",await command.ExecuteScalarAsync()); command.CommandText="SELECT actual_sha256 FROM download_history"; Assert.Equal("A",await command.ExecuteScalarAsync());
    }
    public void Dispose() { if(Directory.Exists(_folder)) Directory.Delete(_folder,true); }
}
