using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using System.Windows.Data;
using System.Windows;
using Microsoft.Win32;
using SoftwareCatalog.Core;
using SoftwareCatalog.Core.Abstractions;
using SoftwareCatalog.Core.Domain;
using SoftwareCatalog.Scanner;
using SoftwareCatalog.Infrastructure.Settings;
using SoftwareCatalog.Infrastructure.Paths;

namespace SoftwareCatalog.UI.ViewModels;
public sealed class MainViewModel : INotifyPropertyChanged
{
    public UpdateCandidateDiscoveryService? CandidateDiscovery { private get; set; }
    public ICommand SearchCandidatesCommand => new AsyncCommand(SearchCandidatesAsync);
    public ICommand AddAliasCommand => new AsyncCommand(AddAliasAsync);
    public ICommand RemoveAliasCommand => new AsyncCommand(RemoveAliasAsync);
    public ICommand ListAliasesCommand => new AsyncCommand(ListAliasesAsync);
    public ICommand ShowMappingsCommand => new AsyncCommand(ShowMappingsAsync);
    public ICommand ToggleMappingCommand => new AsyncCommand(ToggleMappingAsync);
    private readonly AsyncCommand _purgeCommand;
    private readonly AsyncCommand _removeFolderCommand;
    private readonly AsyncCommand _applyRetentionCommand;
    private readonly IScanCatalogRepository _repository; private readonly IProductCatalogRepository _products; private readonly IPortablePathResolver _paths; private readonly CatalogScanner _scanner; private readonly ProductCatalogService _catalog; private readonly UpdateBatchService _batch; private readonly AppSettings _settings; private readonly UpdateDownloadDiscoveryService _downloads; private readonly UpdateDownloadWorkflowService _workflow; private readonly IDownloadHistoryRepository _history; private readonly IAppPathService _appPaths; private readonly InstallerArchiveService _archive; private readonly InstallerRetentionPlanner _retention; private readonly AsyncCommand _downloadUpdateCommand; private CancellationTokenSource? _cts; private ScanRoot? _selected; private SoftwareProduct? _selectedProduct; private InstallerFile? _selectedFile; private string _statusFilter = "Все"; private string _statusText = "Готово"; private double _downloadPercent; private string _downloadProgressText = ""; private double _archivePercent; private string _archiveProgressText = ""; private int _retentionKeepLatestVersions; private bool _isScanning;
    public MainViewModel(IScanCatalogRepository repository, IProductCatalogRepository products, IPortablePathResolver paths, CatalogScanner scanner, ProductCatalogService catalog, UpdateBatchService batch, AppSettings settings, UpdateDownloadDiscoveryService downloads, UpdateDownloadWorkflowService workflow, IDownloadHistoryRepository history, IAppPathService appPaths, InstallerArchiveService archive, InstallerRetentionPlanner retention) { _repository = repository; _products = products; _paths = paths; _scanner = scanner; _catalog = catalog; _batch = batch; _settings = settings; _downloads = downloads; _workflow = workflow; _history = history; _appPaths = appPaths; _archive = archive; _retention = retention; _retentionKeepLatestVersions = Math.Max(1, settings.KeepLatestVersions); _purgeCommand = new AsyncCommand(PurgeAsync, () => SelectedFile?.StorageState == InstallerStorageState.Trashed && !SelectedFile.IsPinned && !IsScanning); _removeFolderCommand = new AsyncCommand(RemoveFolderAsync, () => SelectedScanRoot?.Role == ScanRootRole.User && !IsScanning); _applyRetentionCommand = new AsyncCommand(ApplyRetentionAsync, () => !IsScanning && RetentionItems.Any(item => item.Selected && item.Action == RetentionAction.Archive)); ProductsView = CollectionViewSource.GetDefaultView(Products); ProductsView.Filter = item => item is SoftwareProduct product && MatchesFilter(product); AddFolderCommand = new AsyncCommand(AddFolderAsync); ChangeFolderCommand = new AsyncCommand(ChangeFolderAsync); RemoveFolderCommand = _removeFolderCommand; ScanCommand = new AsyncCommand(ScanAsync); CheckSelectedCommand = new AsyncCommand(CheckSelectedAsync); CheckAllCommand = new AsyncCommand(CheckAllAsync); _downloadUpdateCommand = new AsyncCommand(DownloadUpdateAsync, () => SelectedProduct?.UpdateStatus == UpdateStatus.UpdateAvailable && !IsScanning); DownloadUpdateCommand = _downloadUpdateCommand; DownloadHistoryCommand = new AsyncCommand(ShowDownloadHistoryAsync); OpenDownloadFolderCommand = new AsyncCommand(OpenDownloadFolderAsync); SetWinGetBindingCommand = new AsyncCommand(() => SetBindingAsync("WinGet", "Введите WinGet package ID:")); SetGitHubBindingCommand = new AsyncCommand(() => SetBindingAsync("GitHub", "Введите GitHub owner/repository:")); ClearWinGetBindingCommand = new AsyncCommand(() => ClearBindingAsync("WinGet")); ClearGitHubBindingCommand = new AsyncCommand(() => ClearBindingAsync("GitHub")); ArchiveCommand = new AsyncCommand(() => StorageActionAsync("archive")); RestoreCommand = new AsyncCommand(() => StorageActionAsync("restore")); TrashCommand = new AsyncCommand(() => StorageActionAsync("trash")); PinCommand = new AsyncCommand(TogglePinAsync); RetentionPreviewCommand = new AsyncCommand(PreviewRetentionAsync); CancelCommand = new RelayCommand(() => _cts?.Cancel()); _ = LoadAsync(); }
    public ObservableCollection<ScanRoot> ScanRoots { get; } = []; public ObservableCollection<InstallerFile> Files { get; } = []; public ObservableCollection<SoftwareProduct> Products { get; } = []; public ICollectionView ProductsView { get; } public string[] StatusFilters { get; } = ["Все", "Есть обновления", "Актуальные", "Проблемы"]; public string SelectedStatusFilter { get => _statusFilter; set { _statusFilter = value; OnChanged(); ProductsView.Refresh(); } } public ObservableCollection<InstallerFile> ProductFiles { get; } = []; public ScanRoot? SelectedScanRoot { get => _selected; set { _selected = value; OnChanged(); OnChanged(nameof(SelectedRootAvailability)); _removeFolderCommand.RaiseCanExecuteChanged(); } } public SoftwareProduct? SelectedProduct { get => _selectedProduct; set { _selectedProduct = value; OnChanged(); _downloadUpdateCommand.RaiseCanExecuteChanged(); _ = RefreshProductFilesAsync(); } } public string SelectedRootAvailability => SelectedScanRoot is null ? "" : _paths.GetAvailability(SelectedScanRoot) == ScanRootAvailability.Available ? "Доступна" : "Не найдена"; public string StatusText { get => _statusText; private set { _statusText = value; OnChanged(); } } public double DownloadPercent { get => _downloadPercent; private set { _downloadPercent = value; OnChanged(); } } public string DownloadProgressText { get => _downloadProgressText; private set { _downloadProgressText = value; OnChanged(); } } public double ArchivePercent { get => _archivePercent; private set { _archivePercent = value; OnChanged(); } } public string ArchiveProgressText { get => _archiveProgressText; private set { _archiveProgressText = value; OnChanged(); } } public int RetentionKeepLatestVersions { get => _retentionKeepLatestVersions; set { _retentionKeepLatestVersions = Math.Max(1, value); OnChanged(); } } public bool StoreRelativeToApplication { get; set; } public bool IsScanning { get => _isScanning; private set { _isScanning = value; OnChanged(); _downloadUpdateCommand.RaiseCanExecuteChanged(); _removeFolderCommand.RaiseCanExecuteChanged(); RaiseStorageCanExecuteChanged(); } } public ICommand AddFolderCommand { get; } public ICommand ChangeFolderCommand { get; } public ICommand RemoveFolderCommand { get; } public ICommand ScanCommand { get; } public ICommand CheckSelectedCommand { get; } public ICommand CheckAllCommand { get; } public ICommand DownloadUpdateCommand { get; } public ICommand DownloadHistoryCommand { get; } public ICommand OpenDownloadFolderCommand { get; } public ICommand SetWinGetBindingCommand { get; } public ICommand SetGitHubBindingCommand { get; } public ICommand ClearWinGetBindingCommand { get; } public ICommand ClearGitHubBindingCommand { get; } public ICommand CancelCommand { get; }
    public InstallerFile? SelectedFile { get => _selectedFile; set { _selectedFile = value; OnChanged(); RaiseStorageCanExecuteChanged(); } }
    public ObservableCollection<RetentionPlanItem> RetentionItems { get; } = [];
    public ObservableCollection<ArchiveOperation> ArchiveOperations { get; } = [];
    public ObservableCollection<ArchiveHistoryRow> ArchiveHistoryRows { get; } = [];
    public ICommand ArchiveCommand { get; private set; }
    public ICommand RestoreCommand { get; private set; }
    public ICommand TrashCommand { get; private set; }
    public ICommand PinCommand { get; }
    public ICommand PurgeCommand => _purgeCommand;
    public ICommand RetentionPreviewCommand { get; }
    public ICommand ApplyRetentionCommand => _applyRetentionCommand;
    private bool MatchesFilter(SoftwareProduct product) => ProductStatusFilter.Matches(product, SelectedStatusFilter);
    private async Task LoadAsync() { ConfigureStorageCommands(); foreach (var root in (await _repository.GetScanRootsAsync(CancellationToken.None)).Where(root => root.Role == ScanRootRole.User)) ScanRoots.Add(root); await RefreshFilesAsync(); await RefreshProductsAsync(); }
    private void ConfigureStorageCommands() { ArchiveCommand = new AsyncCommand(() => StorageActionAsync("archive"), () => SelectedFile is { StorageState: InstallerStorageState.Active, IsPinned: false } && !IsScanning); RestoreCommand = new AsyncCommand(() => StorageActionAsync("restore"), () => SelectedFile is { StorageState: InstallerStorageState.Archived or InstallerStorageState.Trashed } && !IsScanning); TrashCommand = new AsyncCommand(() => StorageActionAsync("trash"), () => SelectedFile is { StorageState: InstallerStorageState.Active or InstallerStorageState.Archived, IsPinned: false } && !IsScanning); OnChanged(nameof(ArchiveCommand)); OnChanged(nameof(RestoreCommand)); OnChanged(nameof(TrashCommand)); }
    private void RaiseStorageCanExecuteChanged() { if (ArchiveCommand is AsyncCommand archive) archive.RaiseCanExecuteChanged(); if (RestoreCommand is AsyncCommand restore) restore.RaiseCanExecuteChanged(); if (TrashCommand is AsyncCommand trash) trash.RaiseCanExecuteChanged(); _purgeCommand.RaiseCanExecuteChanged(); _applyRetentionCommand.RaiseCanExecuteChanged(); }
    private async Task AddFolderAsync() { var dialog = new OpenFolderDialog(); if (dialog.ShowDialog() != true) return; var kind = StoreRelativeToApplication ? ScanRootPathKind.RelativeToApplication : ScanRootPathKind.Absolute; var root = await _repository.AddScanRootAsync(_paths.ToStoredPath(dialog.FolderName, kind), kind, true, CancellationToken.None); ScanRoots.Add(root); SelectedScanRoot = root; }
    private async Task ChangeFolderAsync() { if (SelectedScanRoot is null) return; var dialog = new OpenFolderDialog(); if (dialog.ShowDialog() != true) return; var root = SelectedScanRoot; await _repository.UpdateScanRootAsync(root.Id, _paths.ToStoredPath(dialog.FolderName, root.PathKind), root.PathKind, CancellationToken.None); var index = ScanRoots.IndexOf(root); var updated = root with { StoredPath = _paths.ToStoredPath(dialog.FolderName, root.PathKind), UpdatedUtc = DateTimeOffset.UtcNow }; ScanRoots[index] = updated; SelectedScanRoot = updated; }
    private async Task RemoveFolderAsync() { if (SelectedScanRoot?.Role != ScanRootRole.User) return; await _repository.RemoveScanRootAsync(SelectedScanRoot.Id, CancellationToken.None); ScanRoots.Remove(SelectedScanRoot); SelectedScanRoot = null; await RefreshFilesAsync(); }
    internal void SetBusyForTesting(bool isBusy) => IsScanning = isBusy;
    internal Task RefreshProductFilesForTestingAsync() => RefreshProductFilesAsync();
    private async Task ScanAsync() { if (SelectedScanRoot is null || IsScanning) return; IsScanning = true; _cts = new(); StatusText = "Сканирование..."; try { var result = await _scanner.ScanAsync(SelectedScanRoot, new Progress<ScanProgress>(p => StatusText = $"Файлов: {p.Discovered} | Обработано: {p.Processed} | Ошибок: {p.Errors}"), _cts.Token); await _catalog.RegroupAsync(_cts.Token); StatusText = result.Completed ? $"Завершено. Файлов: {result.ProcessedFiles}; ошибок: {result.Errors.Count}" : "Сканирование отменено."; await RefreshFilesAsync(); await RefreshProductsAsync(); } catch (OperationCanceledException) { StatusText = "Операция отменена."; } finally { IsScanning = false; _cts.Dispose(); _cts = null; } }
    private async Task RefreshFilesAsync() { Files.Clear(); foreach (var file in await _repository.GetInstallersAsync(CancellationToken.None)) Files.Add(file); }
    private async Task RefreshProductsAsync() { Products.Clear(); foreach (var product in await _products.GetProductsAsync(CancellationToken.None)) Products.Add(product); }
    private async Task RefreshProductFilesAsync()
    {
        ProductFiles.Clear();
        var view = CollectionViewSource.GetDefaultView(ProductFiles);
        if (view.GroupDescriptions.OfType<PropertyGroupDescription>().All(group => group.PropertyName != nameof(InstallerFile.NormalizedVersion))) view.GroupDescriptions.Add(new PropertyGroupDescription(nameof(InstallerFile.NormalizedVersion)));
        if (SelectedProduct is null) return;
        foreach (var file in await _products.GetInstallersForProductAsync(SelectedProduct.Id, CancellationToken.None)) ProductFiles.Add(file);
    }
    public async Task RefreshArchiveOperationsAsync()
    {
        ArchiveOperations.Clear(); ArchiveHistoryRows.Clear();
        var files = await _repository.GetInstallersAsync(CancellationToken.None);
        foreach (var operation in await _repository.GetArchiveOperationsAsync(null, CancellationToken.None))
        {
            ArchiveOperations.Add(operation);
            var file = files.SingleOrDefault(item => item.Id == operation.InstallerId);
            ArchiveHistoryRows.Add(new ArchiveHistoryRow(operation, file?.ProductName ?? operation.ProductId?.ToString() ?? "Неизвестный продукт", file?.FileName ?? "Удалённый файл"));
        }
    }
    private async Task StorageActionAsync(string action) { if (SelectedFile is null || IsScanning) return; var file = SelectedFile; IsScanning = true; _cts = new(); var progress = new Progress<ArchiveProgress>(UpdateArchiveProgress); try { var result = action switch { "archive" => await _archive.ArchiveAsync(file, _cts.Token, progress), "restore" => await _archive.RestoreAsync(file, null, _cts.Token, progress), _ => await _archive.TrashAsync(file, _cts.Token, progress) }; if (action == "restore" && result.Status == ArchiveOperationStatus.Error) { var dialog = new OpenFolderDialog(); if (dialog.ShowDialog() == true) result = await _archive.RestoreAsync(file, Path.Combine(dialog.FolderName, file.FileName), _cts.Token, progress); } StatusText = result.Status == ArchiveOperationStatus.Completed ? "Операция хранения завершена." : result.Error ?? result.Status.ToString(); await RefreshFilesAsync(); await RefreshProductFilesAsync(); await _catalog.RegroupAsync(_cts.Token); await RefreshProductsAsync(); } catch (OperationCanceledException) { StatusText = "Операция хранения отменена."; } finally { IsScanning = false; _cts.Dispose(); _cts = null; } }
    private async Task TogglePinAsync() { if (SelectedFile is null) return; var selected = SelectedFile; var pinned = !selected.IsPinned; await _repository.SetInstallerPinnedAsync(selected.Id, pinned, CancellationToken.None); SelectedFile = selected with { IsPinned = pinned }; StatusText = pinned ? "Файл закреплён." : "Файл откреплён."; await RefreshFilesAsync(); await RefreshProductFilesAsync(); }
    private async Task PurgeAsync() { if (SelectedFile?.StorageState != InstallerStorageState.Trashed || IsScanning) { StatusText = "Окончательно удалить можно только файл из корзины."; return; } var file = SelectedFile; var prompt = $"Удалить окончательно 1 файл ({file.Size:n0} байт) продукта «{file.ProductName ?? "неизвестный"}»? Восстановить его будет нельзя."; if (MessageBox.Show(prompt, "Подтверждение окончательного удаления", MessageBoxButton.YesNo, MessageBoxImage.Warning) != MessageBoxResult.Yes) return; IsScanning = true; _cts = new(); try { var result = await _archive.PurgeAsync(file, _cts.Token); StatusText = result.Status == ArchiveOperationStatus.Completed ? "Файл окончательно удалён." : result.Error ?? result.Status.ToString(); await RefreshFilesAsync(); await RefreshProductFilesAsync(); await _catalog.RegroupAsync(_cts.Token); await RefreshProductsAsync(); } catch (OperationCanceledException) { StatusText = "Окончательное удаление отменено."; } finally { IsScanning = false; _cts.Dispose(); _cts = null; } }
    private void UpdateArchiveProgress(ArchiveProgress progress) { ArchivePercent = progress.TotalBytes == 0 ? 0 : progress.BytesProcessed * 100d / progress.TotalBytes; ArchiveProgressText = $"{progress.FileName}: {progress.ProcessedFiles}/{progress.TotalFiles}; {progress.BytesProcessed:n0}/{progress.TotalBytes:n0} байт; {progress.Status}"; }
    private async Task PreviewRetentionAsync() { var plan = _retention.CreatePlan(await _repository.GetInstallersAsync(CancellationToken.None), RetentionKeepLatestVersions); RetentionItems.Clear(); foreach (var item in plan.Items) RetentionItems.Add(item); var archive = plan.Items.Count(x => x.Action == RetentionAction.Archive); var duplicates = plan.Items.Count(x => x.Action == RetentionAction.DuplicateCandidate); var review = plan.Items.Count(x => x.Action == RetentionAction.ManualReview); StatusText = $"Предпросмотр retention: архивировать {archive}, дубликаты {duplicates}, проверка {review}; потенциально {plan.EstimatedActiveSpaceFreed:n0} байт."; }
    private async Task ApplyRetentionAsync() { var selected = RetentionItems.Where(item => item.Selected && item.Action == RetentionAction.Archive).ToList(); if (selected.Count == 0) return; var size = selected.Sum(item => item.Installer.Size); var products = selected.Select(item => item.Installer.ProductId).Distinct().Count(); if (MessageBox.Show($"Архивировать {selected.Count} файлов, {size:n0} байт, продуктов: {products}?", "Подтверждение retention", MessageBoxButton.YesNo, MessageBoxImage.Warning) != MessageBoxResult.Yes) return; IsScanning = true; _cts = new(); try { for (var index=0; index<selected.Count; index++) { _cts.Token.ThrowIfCancellationRequested(); var result = await _archive.ArchiveAsync(selected[index].Installer, _cts.Token, new Progress<ArchiveProgress>(p => UpdateArchiveProgress(p with { ProcessedFiles = index, TotalFiles = selected.Count }))); if (result.Status != ArchiveOperationStatus.Completed) StatusText = result.Error ?? result.Status.ToString(); } await _catalog.RegroupAsync(_cts.Token); await RefreshFilesAsync(); await RefreshProductsAsync(); await RefreshProductFilesAsync(); StatusText = "Применение retention завершено."; } catch (OperationCanceledException) { StatusText = "Применение retention отменено."; } finally { IsScanning = false; _cts.Dispose(); _cts = null; } }
    private async Task CheckSelectedAsync() { if (SelectedProduct is null) return; await CheckAsync([SelectedProduct]); }
    private async Task ShowDownloadHistoryAsync() { var entries = await _history.GetDownloadHistoryAsync(CancellationToken.None); new SoftwareCatalog.UI.DownloadHistoryWindow(entries) { Owner = Application.Current.MainWindow }.ShowDialog(); }
    private Task OpenDownloadFolderAsync() { var folder = DownloadDestinationResolver.Resolve(_settings, _appPaths); Directory.CreateDirectory(folder); Process.Start(new ProcessStartInfo("explorer.exe", $"\"{folder}\"") { UseShellExecute = true }); return Task.CompletedTask; }
    private async Task CheckAllAsync() => await CheckAsync(Products);
    private async Task DownloadUpdateAsync() { if (SelectedProduct is null || SelectedProduct.UpdateStatus != UpdateStatus.UpdateAvailable || IsScanning) return; IsScanning = true; _cts = new(); try { StatusText = "Поиск файла обновления..."; var product = SelectedProduct; var resolution = await _downloads.ResolveAsync(product, new UpdateCheckResult(product.UpdateStatus, product.LatestVersion, product.LatestNormalizedVersion), _cts.Token); DownloadCandidate? candidate; if (resolution.Status == DownloadCandidateStatus.Ambiguous) { var dialog = new SoftwareCatalog.UI.DownloadCandidateSelectionWindow(resolution.Candidates) { Owner = Application.Current.MainWindow }; if (dialog.ShowDialog() != true) { StatusText = "Скачивание отменено."; return; } candidate = dialog.SelectedCandidate; } else candidate = resolution.Candidates.SingleOrDefault(); if (candidate is null) { StatusText = resolution.Error ?? "Файл обновления не найден."; return; } var progress = new Progress<DownloadProgress>(p => { DownloadPercent = p.Percent ?? 0; DownloadProgressText = $"{p.FileName}: {p.BytesReceived:n0} / {(p.TotalBytes?.ToString("n0") ?? "?")} байт"; StatusText = $"{p.Status}: {p.FileName} {p.Percent?.ToString("F0") ?? "?"}%"; }); var outcome = await _workflow.ExecuteAsync(product, candidate, progress, _cts.Token); if (outcome.Result.Status == DownloadStatus.ManualConfirmationRequired) { var downloaded = outcome.Result.FinalPath is null ? null : new InstallerMetadataService().Extract(outcome.Result.FinalPath); var details = $"Не удалось надёжно подтвердить metadata.\nОжидаемый продукт: {product.CanonicalName}\nСкачанный продукт: {downloaded?.ProductName ?? "не определено"}\nОжидаемая версия: {product.LatestVersion ?? "не определено"}\nСкачанная версия: {downloaded?.ProductVersion ?? "не определено"}\nСкачанная архитектура: {downloaded?.Architecture ?? "не определено"}\nФайл: {candidate.FileName}\nПровайдер: {candidate.Provider}\nSHA-256: {outcome.Result.Sha256 ?? "не определено"}\n\nИмпортировать файл в каталог?"; if (MessageBox.Show(details, "Требуется подтверждение", MessageBoxButton.YesNo, MessageBoxImage.Warning) == MessageBoxResult.Yes) outcome = outcome with { Result = await _workflow.ConfirmManualImportAsync(product, candidate, outcome.Result, _cts.Token) }; } StatusText = outcome.Result.Status == DownloadStatus.Completed ? $"Скачивание завершено: {outcome.Result.FinalPath}" : outcome.Result.Error ?? outcome.Result.Status.ToString(); await RefreshFilesAsync(); await RefreshProductsAsync(); await RefreshProductFilesAsync(); } finally { IsScanning = false; _cts.Dispose(); _cts = null; } }
    private async Task CheckAsync(IEnumerable<SoftwareProduct> list) { if (IsScanning) return; IsScanning = true; _cts = new(); try { var summary = await _batch.CheckAsync(list, true, _settings.UpdateCheckCacheHours, _settings.MaxUpdateCheckParallelism, _cts.Token); await RefreshProductsAsync(); StatusText = $"Проверка обновлений завершена: {summary.Checked}."; } catch (OperationCanceledException) { StatusText = "Проверка обновлений отменена."; } finally { IsScanning = false; _cts.Dispose(); _cts = null; } }
    private async Task SetBindingAsync(string provider, string prompt) { if (SelectedProduct is null) return; var value = Microsoft.VisualBasic.Interaction.InputBox(prompt, "Software Catalog").Trim(); if (string.IsNullOrWhiteSpace(value)) return; await _products.SetUpdateSourceAsync(new ProductUpdateSource(Guid.NewGuid(), SelectedProduct.Id, provider, value, true, true, MappingSource.Manual, MappingConfidence.Exact), CancellationToken.None); await RefreshProductsAsync(); StatusText = $"Ручная привязка {provider} сохранена."; }
    private async Task ClearBindingAsync(string provider) { if (SelectedProduct is null) return; await _products.ClearUpdateSourcesAsync(SelectedProduct.Id, provider, CancellationToken.None); await RefreshProductsAsync(); StatusText = $"Привязка {provider} очищена."; }
    private async Task SearchCandidatesAsync() { if (SelectedProduct is null || CandidateDiscovery is null) return; var product=SelectedProduct; var candidates = await CandidateDiscovery.SearchAsync(product, true, _settings.UpdateCheckCacheHours, CancellationToken.None); if(candidates.Count==0){StatusText="Кандидаты не найдены.";return;} var dialog=new SoftwareCatalog.UI.UpdateCandidateSelectionWindow(candidates) { Owner=Application.Current.MainWindow }; if(dialog.ShowDialog()!=true || !await SoftwareCatalog.UI.Stage6MappingUiWorkflow.PersistCandidateSelectionAsync(product.Id,dialog.SelectedCandidate,mapping=>_products.SetUpdateSourceAsync(mapping,CancellationToken.None))){StatusText="Mapping не изменён.";return;} StatusText = "Ручная привязка сохранена."; await RefreshProductsAsync(); }
    private Task AddAliasAsync() => ListAliasesAsync();
    private Task RemoveAliasAsync() => ListAliasesAsync();
    private async Task ListAliasesAsync() { if(SelectedProduct is null)return; var product=SelectedProduct; var aliases=await _products.GetProductAliasesAsync(product.Id,CancellationToken.None); new SoftwareCatalog.UI.AliasManagementWindow(aliases,async value=>{var alias=new ProductAlias(product.Id,value,new ProductNormalizer().Normalize(value),MappingSource.Manual);await _products.SetProductAliasAsync(alias,CancellationToken.None);return alias;},alias=>_products.RemoveProductAliasAsync(product.Id,alias.NormalizedAlias,CancellationToken.None)).ShowDialog(); }
    private async Task ShowMappingsAsync() { if(SelectedProduct is null)return; var product=SelectedProduct; var mappings=await _products.GetUpdateSourcesAsync(product.Id,CancellationToken.None); new SoftwareCatalog.UI.MappingManagementWindow(mappings,product.LastCheckedUtc,async mapping=>{await _products.SetUpdateSourceAsync(mapping,CancellationToken.None);await RefreshProductsAsync();},mapping=>_products.ClearUpdateSourcesAsync(product.Id,mapping.ProviderType,CancellationToken.None),SearchCandidatesAsync).ShowDialog(); }
    private async Task ToggleMappingAsync() { if(SelectedProduct is null)return; var mappings=await _products.GetUpdateSourcesAsync(SelectedProduct.Id,CancellationToken.None); var provider=Microsoft.VisualBasic.Interaction.InputBox("Provider для Enable/Disable:\n"+string.Join("\n",mappings.Select(x=>x.ProviderType)),"Mappings").Trim(); var mapping=mappings.FirstOrDefault(x=>x.ProviderType.Equals(provider,StringComparison.OrdinalIgnoreCase)); if(mapping is null)return; await _products.SetUpdateSourceAsync(mapping with { Enabled=!mapping.Enabled },CancellationToken.None);StatusText=$"Mapping {provider}: {(!mapping.Enabled ? "включён" : "выключен")}."; }
    public event PropertyChangedEventHandler? PropertyChanged; private void OnChanged([CallerMemberName] string? name = null) { PropertyChanged?.Invoke(this, new(name)); if (name == nameof(IsScanning)) RaiseStorageCanExecuteChanged(); }
}
public sealed class RelayCommand(Action execute) : ICommand { public event EventHandler? CanExecuteChanged { add { } remove { } } public bool CanExecute(object? parameter) => true; public void Execute(object? parameter) => execute(); }
public sealed class AsyncCommand(Func<Task> execute, Func<bool>? canExecute = null) : ICommand { private readonly Func<bool> _canExecute = canExecute ?? (() => true); public event EventHandler? CanExecuteChanged; public bool CanExecute(object? parameter) => _canExecute(); public async void Execute(object? parameter) => await execute(); public void RaiseCanExecuteChanged() => CanExecuteChanged?.Invoke(this, EventArgs.Empty); }
public sealed record ArchiveHistoryRow(ArchiveOperation Operation, string Product, string File)
{
    public ArchiveOperationType OperationType => Operation.OperationType;
    public InstallerStorageState FromState => Operation.FromState;
    public InstallerStorageState? ToState => Operation.ToState;
    public ArchiveOperationStatus Status => Operation.Status;
    public DateTimeOffset StartedUtc => Operation.StartedUtc;
    public DateTimeOffset? CompletedUtc => Operation.CompletedUtc;
    public string? Error => Operation.Error;
}
