using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using System.Windows.Data;
using System.Windows;
using Microsoft.Win32;
using SoftwareCatalog.Core;
using SoftwareCatalog.Core.Abstractions;
using SoftwareCatalog.Core.Domain;
using SoftwareCatalog.Scanner;
using SoftwareCatalog.Infrastructure.Settings;
using SoftwareCatalog.Infrastructure.Paths;

namespace SoftwareCatalog.UI.ViewModels;
public sealed class MainViewModel : INotifyPropertyChanged
{
    private readonly IScanCatalogRepository _repository; private readonly IProductCatalogRepository _products; private readonly IPortablePathResolver _paths; private readonly CatalogScanner _scanner; private readonly ProductCatalogService _catalog; private readonly UpdateBatchService _batch; private readonly AppSettings _settings; private readonly UpdateDownloadDiscoveryService _downloads; private readonly UpdateDownloadWorkflowService _workflow; private readonly IDownloadHistoryRepository _history; private readonly IAppPathService _appPaths; private readonly AsyncCommand _downloadUpdateCommand; private CancellationTokenSource? _cts; private ScanRoot? _selected; private SoftwareProduct? _selectedProduct; private string _statusFilter = "Все"; private string _statusText = "Готово"; private double _downloadPercent; private string _downloadProgressText = ""; private bool _isScanning;
    public MainViewModel(IScanCatalogRepository repository, IProductCatalogRepository products, IPortablePathResolver paths, CatalogScanner scanner, ProductCatalogService catalog, UpdateBatchService batch, AppSettings settings, UpdateDownloadDiscoveryService downloads, UpdateDownloadWorkflowService workflow, IDownloadHistoryRepository history, IAppPathService appPaths) { _repository = repository; _products = products; _paths = paths; _scanner = scanner; _catalog = catalog; _batch = batch; _settings = settings; _downloads = downloads; _workflow = workflow; _history = history; _appPaths = appPaths; ProductsView = CollectionViewSource.GetDefaultView(Products); ProductsView.Filter = item => item is SoftwareProduct product && MatchesFilter(product); AddFolderCommand = new AsyncCommand(AddFolderAsync); ChangeFolderCommand = new AsyncCommand(ChangeFolderAsync); RemoveFolderCommand = new AsyncCommand(RemoveFolderAsync); ScanCommand = new AsyncCommand(ScanAsync); CheckSelectedCommand = new AsyncCommand(CheckSelectedAsync); CheckAllCommand = new AsyncCommand(CheckAllAsync); _downloadUpdateCommand = new AsyncCommand(DownloadUpdateAsync, () => SelectedProduct?.UpdateStatus == UpdateStatus.UpdateAvailable && !IsScanning); DownloadUpdateCommand = _downloadUpdateCommand; DownloadHistoryCommand = new AsyncCommand(ShowDownloadHistoryAsync); OpenDownloadFolderCommand = new AsyncCommand(OpenDownloadFolderAsync); SetWinGetBindingCommand = new AsyncCommand(() => SetBindingAsync("WinGet", "Введите WinGet package ID:")); SetGitHubBindingCommand = new AsyncCommand(() => SetBindingAsync("GitHub", "Введите GitHub owner/repository:")); ClearWinGetBindingCommand = new AsyncCommand(() => ClearBindingAsync("WinGet")); ClearGitHubBindingCommand = new AsyncCommand(() => ClearBindingAsync("GitHub")); CancelCommand = new RelayCommand(() => _cts?.Cancel()); _ = LoadAsync(); }
    public ObservableCollection<ScanRoot> ScanRoots { get; } = []; public ObservableCollection<InstallerFile> Files { get; } = []; public ObservableCollection<SoftwareProduct> Products { get; } = []; public ICollectionView ProductsView { get; } public string[] StatusFilters { get; } = ["Все", "Есть обновления", "Актуальные", "Проблемы"]; public string SelectedStatusFilter { get => _statusFilter; set { _statusFilter = value; OnChanged(); ProductsView.Refresh(); } } public ObservableCollection<InstallerFile> ProductFiles { get; } = []; public ScanRoot? SelectedScanRoot { get => _selected; set { _selected = value; OnChanged(); OnChanged(nameof(SelectedRootAvailability)); } } public SoftwareProduct? SelectedProduct { get => _selectedProduct; set { _selectedProduct = value; OnChanged(); _downloadUpdateCommand.RaiseCanExecuteChanged(); _ = RefreshProductFilesAsync(); } } public string SelectedRootAvailability => SelectedScanRoot is null ? "" : _paths.GetAvailability(SelectedScanRoot) == ScanRootAvailability.Available ? "Доступна" : "Не найдена"; public string StatusText { get => _statusText; private set { _statusText = value; OnChanged(); } } public double DownloadPercent { get => _downloadPercent; private set { _downloadPercent = value; OnChanged(); } } public string DownloadProgressText { get => _downloadProgressText; private set { _downloadProgressText = value; OnChanged(); } } public bool StoreRelativeToApplication { get; set; } public bool IsScanning { get => _isScanning; private set { _isScanning = value; OnChanged(); _downloadUpdateCommand.RaiseCanExecuteChanged(); } } public ICommand AddFolderCommand { get; } public ICommand ChangeFolderCommand { get; } public ICommand RemoveFolderCommand { get; } public ICommand ScanCommand { get; } public ICommand CheckSelectedCommand { get; } public ICommand CheckAllCommand { get; } public ICommand DownloadUpdateCommand { get; } public ICommand DownloadHistoryCommand { get; } public ICommand OpenDownloadFolderCommand { get; } public ICommand SetWinGetBindingCommand { get; } public ICommand SetGitHubBindingCommand { get; } public ICommand ClearWinGetBindingCommand { get; } public ICommand ClearGitHubBindingCommand { get; } public ICommand CancelCommand { get; }
    private bool MatchesFilter(SoftwareProduct product) => ProductStatusFilter.Matches(product, SelectedStatusFilter);
    private async Task LoadAsync() { foreach (var root in await _repository.GetScanRootsAsync(CancellationToken.None)) ScanRoots.Add(root); await RefreshFilesAsync(); await RefreshProductsAsync(); }
    private async Task AddFolderAsync() { var dialog = new OpenFolderDialog(); if (dialog.ShowDialog() != true) return; var kind = StoreRelativeToApplication ? ScanRootPathKind.RelativeToApplication : ScanRootPathKind.Absolute; var root = await _repository.AddScanRootAsync(_paths.ToStoredPath(dialog.FolderName, kind), kind, true, CancellationToken.None); ScanRoots.Add(root); SelectedScanRoot = root; }
    private async Task ChangeFolderAsync() { if (SelectedScanRoot is null) return; var dialog = new OpenFolderDialog(); if (dialog.ShowDialog() != true) return; var root = SelectedScanRoot; await _repository.UpdateScanRootAsync(root.Id, _paths.ToStoredPath(dialog.FolderName, root.PathKind), root.PathKind, CancellationToken.None); var index = ScanRoots.IndexOf(root); var updated = root with { StoredPath = _paths.ToStoredPath(dialog.FolderName, root.PathKind), UpdatedUtc = DateTimeOffset.UtcNow }; ScanRoots[index] = updated; SelectedScanRoot = updated; }
    private async Task RemoveFolderAsync() { if (SelectedScanRoot is null) return; await _repository.RemoveScanRootAsync(SelectedScanRoot.Id, CancellationToken.None); ScanRoots.Remove(SelectedScanRoot); SelectedScanRoot = null; await RefreshFilesAsync(); }
    private async Task ScanAsync() { if (SelectedScanRoot is null || IsScanning) return; IsScanning = true; _cts = new(); StatusText = "Сканирование..."; try { var result = await _scanner.ScanAsync(SelectedScanRoot, new Progress<ScanProgress>(p => StatusText = $"Файлов: {p.Discovered} | Обработано: {p.Processed} | Ошибок: {p.Errors}"), _cts.Token); await _catalog.RegroupAsync(_cts.Token); StatusText = result.Completed ? $"Завершено. Файлов: {result.ProcessedFiles}; ошибок: {result.Errors.Count}" : "Сканирование отменено."; await RefreshFilesAsync(); await RefreshProductsAsync(); } catch (OperationCanceledException) { StatusText = "Операция отменена."; } finally { IsScanning = false; _cts.Dispose(); _cts = null; } }
    private async Task RefreshFilesAsync() { Files.Clear(); foreach (var file in await _repository.GetInstallersAsync(CancellationToken.None)) Files.Add(file); }
    private async Task RefreshProductsAsync() { Products.Clear(); foreach (var product in await _products.GetProductsAsync(CancellationToken.None)) Products.Add(product); }
    private async Task RefreshProductFilesAsync() { ProductFiles.Clear(); if (SelectedProduct is null) return; foreach (var file in await _products.GetInstallersForProductAsync(SelectedProduct.Id, CancellationToken.None)) ProductFiles.Add(file); }
    private async Task CheckSelectedAsync() { if (SelectedProduct is null) return; await CheckAsync([SelectedProduct]); }
    private async Task ShowDownloadHistoryAsync() { var entries = await _history.GetDownloadHistoryAsync(CancellationToken.None); new SoftwareCatalog.UI.DownloadHistoryWindow(entries) { Owner = Application.Current.MainWindow }.ShowDialog(); }
    private Task OpenDownloadFolderAsync() { var folder = DownloadDestinationResolver.Resolve(_settings, _appPaths); Directory.CreateDirectory(folder); Process.Start(new ProcessStartInfo("explorer.exe", $"\"{folder}\"") { UseShellExecute = true }); return Task.CompletedTask; }
    private async Task CheckAllAsync() => await CheckAsync(Products);
    private async Task DownloadUpdateAsync() { if (SelectedProduct is null || SelectedProduct.UpdateStatus != UpdateStatus.UpdateAvailable || IsScanning) return; IsScanning = true; _cts = new(); try { StatusText = "Поиск файла обновления..."; var product = SelectedProduct; var resolution = await _downloads.ResolveAsync(product, new UpdateCheckResult(product.UpdateStatus, product.LatestVersion, product.LatestNormalizedVersion), _cts.Token); DownloadCandidate? candidate; if (resolution.Status == DownloadCandidateStatus.Ambiguous) { var dialog = new SoftwareCatalog.UI.DownloadCandidateSelectionWindow(resolution.Candidates) { Owner = Application.Current.MainWindow }; if (dialog.ShowDialog() != true) { StatusText = "Скачивание отменено."; return; } candidate = dialog.SelectedCandidate; } else candidate = resolution.Candidates.SingleOrDefault(); if (candidate is null) { StatusText = resolution.Error ?? "Файл обновления не найден."; return; } var progress = new Progress<DownloadProgress>(p => { DownloadPercent = p.Percent ?? 0; DownloadProgressText = $"{p.FileName}: {p.BytesReceived:n0} / {(p.TotalBytes?.ToString("n0") ?? "?")} байт"; StatusText = $"{p.Status}: {p.FileName} {p.Percent?.ToString("F0") ?? "?"}%"; }); var outcome = await _workflow.ExecuteAsync(product, candidate, progress, _cts.Token); if (outcome.Result.Status == DownloadStatus.ManualConfirmationRequired) { var downloaded = outcome.Result.FinalPath is null ? null : new InstallerMetadataService().Extract(outcome.Result.FinalPath); var details = $"Не удалось надёжно подтвердить metadata.\nОжидаемый продукт: {product.CanonicalName}\nСкачанный продукт: {downloaded?.ProductName ?? "не определено"}\nОжидаемая версия: {product.LatestVersion ?? "не определено"}\nСкачанная версия: {downloaded?.ProductVersion ?? "не определено"}\nСкачанная архитектура: {downloaded?.Architecture ?? "не определено"}\nФайл: {candidate.FileName}\nПровайдер: {candidate.Provider}\nSHA-256: {outcome.Result.Sha256 ?? "не определено"}\n\nИмпортировать файл в каталог?"; if (MessageBox.Show(details, "Требуется подтверждение", MessageBoxButton.YesNo, MessageBoxImage.Warning) == MessageBoxResult.Yes) outcome = outcome with { Result = await _workflow.ConfirmManualImportAsync(product, candidate, outcome.Result, _cts.Token) }; } StatusText = outcome.Result.Status == DownloadStatus.Completed ? $"Скачивание завершено: {outcome.Result.FinalPath}" : outcome.Result.Error ?? outcome.Result.Status.ToString(); await RefreshFilesAsync(); await RefreshProductsAsync(); await RefreshProductFilesAsync(); } finally { IsScanning = false; _cts.Dispose(); _cts = null; } }
    private async Task CheckAsync(IEnumerable<SoftwareProduct> list) { if (IsScanning) return; IsScanning = true; _cts = new(); try { var summary = await _batch.CheckAsync(list, true, _settings.UpdateCheckCacheHours, _settings.MaxUpdateCheckParallelism, _cts.Token); await RefreshProductsAsync(); StatusText = $"Проверка обновлений завершена: {summary.Checked}."; } catch (OperationCanceledException) { StatusText = "Проверка обновлений отменена."; } finally { IsScanning = false; _cts.Dispose(); _cts = null; } }
    private async Task SetBindingAsync(string provider, string prompt) { if (SelectedProduct is null) return; var value = Microsoft.VisualBasic.Interaction.InputBox(prompt, "Software Catalog").Trim(); if (string.IsNullOrWhiteSpace(value)) return; await _products.SetUpdateSourceAsync(new ProductUpdateSource(Guid.NewGuid(), SelectedProduct.Id, provider, value, true, true), CancellationToken.None); await RefreshProductsAsync(); StatusText = $"Привязка {provider} сохранена."; }
    private async Task ClearBindingAsync(string provider) { if (SelectedProduct is null) return; await _products.ClearUpdateSourcesAsync(SelectedProduct.Id, provider, CancellationToken.None); await RefreshProductsAsync(); StatusText = $"Привязка {provider} очищена."; }
    public event PropertyChangedEventHandler? PropertyChanged; private void OnChanged([CallerMemberName] string? name = null) => PropertyChanged?.Invoke(this, new(name));
}
public sealed class RelayCommand(Action execute) : ICommand { public event EventHandler? CanExecuteChanged { add { } remove { } } public bool CanExecute(object? parameter) => true; public void Execute(object? parameter) => execute(); }
public sealed class AsyncCommand(Func<Task> execute, Func<bool>? canExecute = null) : ICommand { private readonly Func<bool> _canExecute = canExecute ?? (() => true); public event EventHandler? CanExecuteChanged; public bool CanExecute(object? parameter) => _canExecute(); public async void Execute(object? parameter) => await execute(); public void RaiseCanExecuteChanged() => CanExecuteChanged?.Invoke(this, EventArgs.Empty); }
