using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Microsoft.Win32;
using SoftwareCatalog.Core;
using SoftwareCatalog.Core.Abstractions;
using SoftwareCatalog.Core.Domain;
using SoftwareCatalog.Scanner;

namespace SoftwareCatalog.UI.ViewModels;
public sealed class MainViewModel : INotifyPropertyChanged
{
    private readonly IScanCatalogRepository _repository; private readonly IProductCatalogRepository _products; private readonly IPortablePathResolver _paths; private readonly CatalogScanner _scanner; private readonly ProductCatalogService _catalog; private readonly UpdateDiscoveryService _updates; private CancellationTokenSource? _cts; private ScanRoot? _selected; private SoftwareProduct? _selectedProduct; private string _statusText = "Готово";
    public MainViewModel(IScanCatalogRepository repository, IProductCatalogRepository products, IPortablePathResolver paths, CatalogScanner scanner, ProductCatalogService catalog, UpdateDiscoveryService updates) { _repository = repository; _products = products; _paths = paths; _scanner = scanner; _catalog = catalog; _updates = updates; AddFolderCommand = new AsyncCommand(AddFolderAsync); ChangeFolderCommand = new AsyncCommand(ChangeFolderAsync); RemoveFolderCommand = new AsyncCommand(RemoveFolderAsync); ScanCommand = new AsyncCommand(ScanAsync); CheckSelectedCommand = new AsyncCommand(CheckSelectedAsync); CheckAllCommand = new AsyncCommand(CheckAllAsync); CancelCommand = new RelayCommand(() => _cts?.Cancel()); _ = LoadAsync(); }
    public ObservableCollection<ScanRoot> ScanRoots { get; } = []; public ObservableCollection<InstallerFile> Files { get; } = []; public ObservableCollection<SoftwareProduct> Products { get; } = []; public ObservableCollection<InstallerFile> ProductFiles { get; } = []; public ScanRoot? SelectedScanRoot { get => _selected; set { _selected = value; OnChanged(); OnChanged(nameof(SelectedRootAvailability)); } } public SoftwareProduct? SelectedProduct { get => _selectedProduct; set { _selectedProduct = value; OnChanged(); _ = RefreshProductFilesAsync(); } } public string SelectedRootAvailability => SelectedScanRoot is null ? "" : _paths.GetAvailability(SelectedScanRoot) == ScanRootAvailability.Available ? "Доступна" : "Не найдена"; public string StatusText { get => _statusText; private set { _statusText = value; OnChanged(); } } public bool StoreRelativeToApplication { get; set; } public bool IsScanning { get; private set; } public ICommand AddFolderCommand { get; } public ICommand ChangeFolderCommand { get; } public ICommand RemoveFolderCommand { get; } public ICommand ScanCommand { get; } public ICommand CheckSelectedCommand { get; } public ICommand CheckAllCommand { get; } public ICommand CancelCommand { get; }
    private async Task LoadAsync() { foreach (var root in await _repository.GetScanRootsAsync(CancellationToken.None)) ScanRoots.Add(root); await RefreshFilesAsync(); await RefreshProductsAsync(); }
    private async Task AddFolderAsync() { var dialog = new OpenFolderDialog(); if (dialog.ShowDialog() != true) return; var kind = StoreRelativeToApplication ? ScanRootPathKind.RelativeToApplication : ScanRootPathKind.Absolute; var root = await _repository.AddScanRootAsync(_paths.ToStoredPath(dialog.FolderName, kind), kind, true, CancellationToken.None); ScanRoots.Add(root); SelectedScanRoot = root; }
    private async Task ChangeFolderAsync() { if (SelectedScanRoot is null) return; var dialog = new OpenFolderDialog(); if (dialog.ShowDialog() != true) return; var root = SelectedScanRoot; await _repository.UpdateScanRootAsync(root.Id, _paths.ToStoredPath(dialog.FolderName, root.PathKind), root.PathKind, CancellationToken.None); var index = ScanRoots.IndexOf(root); var updated = root with { StoredPath = _paths.ToStoredPath(dialog.FolderName, root.PathKind), UpdatedUtc = DateTimeOffset.UtcNow }; ScanRoots[index] = updated; SelectedScanRoot = updated; }
    private async Task RemoveFolderAsync() { if (SelectedScanRoot is null) return; await _repository.RemoveScanRootAsync(SelectedScanRoot.Id, CancellationToken.None); ScanRoots.Remove(SelectedScanRoot); SelectedScanRoot = null; await RefreshFilesAsync(); }
    private async Task ScanAsync() { if (SelectedScanRoot is null || IsScanning) return; IsScanning = true; _cts = new(); StatusText = "Сканирование..."; try { var result = await _scanner.ScanAsync(SelectedScanRoot, new Progress<ScanProgress>(p => StatusText = $"Файлов: {p.Discovered} | Обработано: {p.Processed} | Ошибок: {p.Errors}"), _cts.Token); await _catalog.RegroupAsync(_cts.Token); StatusText = result.Completed ? $"Завершено. Файлов: {result.ProcessedFiles}; ошибок: {result.Errors.Count}" : "Сканирование отменено."; await RefreshFilesAsync(); await RefreshProductsAsync(); } catch (OperationCanceledException) { StatusText = "Операция отменена."; } finally { IsScanning = false; _cts.Dispose(); _cts = null; } }
    private async Task RefreshFilesAsync() { Files.Clear(); foreach (var file in await _repository.GetInstallersAsync(CancellationToken.None)) Files.Add(file); }
    private async Task RefreshProductsAsync() { Products.Clear(); foreach (var product in await _products.GetProductsAsync(CancellationToken.None)) Products.Add(product); }
    private async Task RefreshProductFilesAsync() { ProductFiles.Clear(); if (SelectedProduct is null) return; foreach (var file in await _products.GetInstallersForProductAsync(SelectedProduct.Id, CancellationToken.None)) ProductFiles.Add(file); }
    private async Task CheckSelectedAsync() { if (SelectedProduct is null) return; await CheckAsync([SelectedProduct]); }
    private async Task CheckAllAsync() => await CheckAsync(Products);
    private async Task CheckAsync(IEnumerable<SoftwareProduct> list) { if (IsScanning) return; IsScanning = true; _cts = new(); try { foreach (var product in list) { _cts.Token.ThrowIfCancellationRequested(); StatusText = $"Проверка обновлений: {product.CanonicalName}"; await _updates.CheckAsync(product, true, 12, _cts.Token); } await RefreshProductsAsync(); StatusText = "Проверка обновлений завершена."; } catch (OperationCanceledException) { StatusText = "Проверка обновлений отменена."; } finally { IsScanning = false; _cts.Dispose(); _cts = null; } }
    public event PropertyChangedEventHandler? PropertyChanged; private void OnChanged([CallerMemberName] string? name = null) => PropertyChanged?.Invoke(this, new(name));
}
public sealed class RelayCommand(Action execute) : ICommand { public event EventHandler? CanExecuteChanged { add { } remove { } } public bool CanExecute(object? parameter) => true; public void Execute(object? parameter) => execute(); }
public sealed class AsyncCommand(Func<Task> execute) : ICommand { public event EventHandler? CanExecuteChanged { add { } remove { } } public bool CanExecute(object? parameter) => true; public async void Execute(object? parameter) => await execute(); }
